language: node_js

node_js: '16'

cache: npm

git:
  depth: false

branch:
  only:
    - master

script:
  - git config --local user.name "My CSC Team"
  - git config --local user.email "suiteamsui@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

before_deploy:
  - npm install
  - npm run build
  - npm run style-dictionary:build:prod

deploy:
  - provider: script
    script: if [ "$GH_TOKEN" != "false" ];then sleep 10 && npx auto latest && sleep 10; fi;
    skip-cleanup: true
    on:
      tags: true
      branch: master

after_deploy:
  - npm run deploy:documentation
