/**
 * Tag-name-map generator (ADR-0015 IDE artifacts, TypeScript flavor).
 *
 * Emits src/tag-name-map.ts: one typed element interface per component
 * (props, exposed methods, typed add/removeEventListener from the event map)
 * plus a global `HTMLElementTagNameMap` augmentation, so framework-free
 * TypeScript consumers get typed `document.createElement('c-button')` /
 * `querySelector('c-button')`, and wrapper codegen has element types to
 * anchor on.
 *
 * The file is generated into src/ (not dist/) because vue-tsc emits the
 * package's public types from src — it is committed, regenerated by the
 * analyzer, and drift-checked in --strict mode.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import ts from 'typescript';

const HEADER = `/* eslint-disable */
/**
 * GENERATED by scripts/analyzer/tag-map.mjs — do not edit.
 * Regenerate with \`pnpm run docs:manifest\`.
 *
 * Typed element interfaces for every registered custom element, plus the
 * global \`HTMLElementTagNameMap\` augmentation that makes
 * \`document.createElement('c-button')\` and \`querySelector('c-button')\`
 * return the typed element.
 */
`;

/** Escape a JSDoc body so a stray comment terminator can't break the file. */
const jsdoc = (description, indent) => {
  if (!description) return '';

  const body = description.replace(/\*\//g, '*\\/');

  const lines = body.split('\n');

  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`;

  return `${indent}/**\n${lines
    .map((line) => `${indent} * ${line}`.trimEnd())
    .join('\n')}\n${indent} */\n`;
};

/** Quote a member key when it is not a plain identifier (e.g. update:value). */
const memberKey = (name) =>
  /^[A-Za-z_$][\w$]*$/.test(name) ? name : `'${name}'`;

const literalType = (text) => {
  if (text === 'true' || text === 'false') return 'boolean';

  if (/^-?\d/.test(text)) return 'number';

  if (/^['"`]/.test(text)) return 'string';

  return 'unknown';
};

/**
 * Normalize a defineExpose signature (`(reset = false)`, `(): DOMRect | null`)
 * into interface-method syntax: default-valued params become optional typed
 * params, and a missing return type becomes `void`.
 */
const methodSignature = (signature) => {
  const source = signature || '()';

  const close = source.lastIndexOf(')');

  const params = source
    .slice(1, close)
    .split(',')
    .map((param) => param.trim())
    .filter(Boolean)
    .map((param) => {
      const withDefault = param.match(/^(\w+)\s*=\s*(.+)$/);

      if (withDefault) {
        return `${withDefault[1]}?: ${literalType(withDefault[2].trim())}`;
      }

      return param;
    })
    .join(', ');

  const ret = source.slice(close + 1).trim();

  return `(${params})${ret || ': void'}`;
};

/** The manifest's display type: expanded literal union when available. */
const fieldType = (prop) => prop.typeExpanded ?? prop.type;

/** name → import path for every public package type (ADR-0015). */
const publicTypeOwners = (components, publicTypes) => {
  const owners = new Map();

  for (const type of publicTypes) {
    const owner = type.owner
      ? components.find((c) => c.tagName === type.owner)
      : null;

    const modulePath = owner
      ? `./${path.posix.relative('src', owner.modulePath.replace(/\\/g, '/'))}`
      : './types';

    owners.set(type.name, modulePath);
  }

  return owners;
};

/**
 * name → declaration text for every top-level type alias / interface / enum
 * in the component scripts. Props and event details may reference local,
 * non-exported aliases (e.g. `AccordionValue`); those get inlined into the
 * generated file. A name declared differently in two components is a hard
 * error — inlining would silently pick one.
 */
const localDeclarations = (components) => {
  const decls = new Map();

  for (const component of components) {
    if (!component.script) continue;

    const sf = ts.createSourceFile(
      component.modulePath,
      component.script,
      ts.ScriptTarget.Latest,
      true,
      ts.ScriptKind.TS,
    );

    for (const statement of sf.statements) {
      if (
        !ts.isTypeAliasDeclaration(statement) &&
        !ts.isInterfaceDeclaration(statement) &&
        !ts.isEnumDeclaration(statement)
      ) {
        continue;
      }

      const name = statement.name.text;

      const text = statement.getText(sf).replace(/^export\s+/, '');

      const existing = decls.get(name);

      if (existing && existing !== text) {
        throw new Error(
          `tag-name-map: local type "${name}" is declared differently in two components — rename one`,
        );
      }

      decls.set(name, text);
    }
  }

  return decls;
};

const identifiersIn = (text) =>
  [...text.matchAll(/\b[A-Z][A-Za-z0-9]*\b/g)].map((m) => m[0]);

/**
 * Resolve every referenced type name to an import (public types) or an
 * inlined local declaration, chasing references transitively (an inlined
 * alias may itself reference another local). Unknown names are assumed
 * global (`DOMRect`, `ArrayLike`, …).
 */
const resolveReferences = (texts, components, publicTypes) => {
  const owners = publicTypeOwners(components, publicTypes);

  const locals = localDeclarations(components);

  const imported = new Map();

  const inlined = new Map();

  const queue = texts.flatMap(identifiersIn);

  const seen = new Set();

  while (queue.length) {
    const name = queue.shift();

    if (seen.has(name)) continue;

    seen.add(name);

    if (owners.has(name)) {
      imported.set(name, owners.get(name));
    } else if (locals.has(name)) {
      const text = locals.get(name);

      inlined.set(name, text);
      queue.push(...identifiersIn(text).filter((n) => n !== name));
    }
  }

  const byModule = new Map();

  for (const name of [...imported.keys()].sort()) {
    const modulePath = imported.get(name);

    if (!byModule.has(modulePath)) byModule.set(modulePath, []);

    byModule.get(modulePath).push(name);
  }

  const imports = [...byModule.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([modulePath, names]) =>
        `import type { ${names.join(', ')} } from '${modulePath}';`,
    )
    .join('\n');

  const inlinedBlock = [...inlined.keys()]
    .sort()
    .map((name) => inlined.get(name))
    .join('\n\n');

  return { imports, inlinedBlock };
};

const listenerOverloads = (
  elementName,
  eventMapName,
) => `  addEventListener<K extends keyof ${eventMapName}>(
    type: K,
    listener: (this: ${elementName}, ev: ${eventMapName}[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof ${eventMapName}>(
    type: K,
    listener: (this: ${elementName}, ev: ${eventMapName}[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;`;

export const renderTagNameMap = (components, publicTypes) => {
  const sorted = [...components].sort((a, b) =>
    a.tagName.localeCompare(b.tagName),
  );

  const blocks = [];

  const typeTexts = [];

  for (const component of sorted) {
    const elementName = `${component.className}Element`;

    const eventMapName = `${elementName}EventMap`;

    let block = '';

    if (component.events.length) {
      block += `/** Events dispatched by \`<${component.tagName}>\`. */\n`;
      block += `export interface ${eventMapName} {\n`;

      for (const event of component.events) {
        typeTexts.push(event.detailType);
        block += jsdoc(event.description, '  ');
        block += `  ${memberKey(event.name)}: CustomEvent<${event.detailType}>;\n`;
      }

      block += `}\n\n`;
    }

    // Vue's defineCustomElement installs an own accessor for every declared
    // prop, shadowing any same-named HTMLElement member (e.g. c-text-field's
    // `autocorrect` string union over the DOM lib's boolean) — so the base
    // type drops the shadowed names instead of fighting them.
    const base = component.props.length
      ? `Omit<HTMLElement, ${component.props
          .map((prop) => `'${prop.name}'`)
          .join(' | ')}>`
      : 'HTMLElement';

    block += jsdoc(component.description, '');
    block += `export interface ${elementName} extends ${base} {\n`;

    for (const prop of component.props) {
      typeTexts.push(fieldType(prop));
      block += jsdoc(prop.description, '  ');
      block += `  ${memberKey(prop.name)}${prop.optional ? '?' : ''}: ${fieldType(prop)};\n`;
    }

    for (const method of component.methods) {
      typeTexts.push(method.signature ?? '');
      block += jsdoc(method.description, '  ');
      block += `  ${memberKey(method.name)}${methodSignature(method.signature)};\n`;
    }

    if (component.events.length) {
      block += listenerOverloads(elementName, eventMapName);
      block += '\n';
    }

    block += `}\n`;

    blocks.push(block);
  }

  const map = sorted
    .map((c) => `    '${c.tagName}': ${c.className}Element;`)
    .join('\n');

  const { imports, inlinedBlock } = resolveReferences(
    typeTexts,
    components,
    publicTypes,
  );

  const parts = [HEADER];

  if (imports) parts.push(imports, '');

  if (inlinedBlock) {
    parts.push(
      '// Local (non-exported) types referenced by the interfaces, inlined.',
      inlinedBlock,
      '',
    );
  }

  parts.push(
    blocks.join('\n'),
    `declare global {\n  interface HTMLElementTagNameMap {\n${map}\n  }\n}\n`,
  );

  return parts.join('\n');
};

/**
 * Write src/tag-name-map.ts when its content changed. Returns whether the
 * committed file was stale — --strict treats that as a lint error so CI
 * catches a map that no longer matches the component sources.
 */
export const emitTagNameMap = (components, publicTypes, packageRoot) => {
  const target = path.join(packageRoot, 'src/tag-name-map.ts');

  const next = renderTagNameMap(components, publicTypes);

  const previous = existsSync(target) ? readFileSync(target, 'utf8') : '';

  if (previous === next) return { changed: false, target };

  writeFileSync(target, next);

  return { changed: true, target };
};
