/* eslint-disable */
/**
 * GENERATED by scripts/analyzer/tag-map.mjs — do not edit.
 * Regenerate with `pnpm run docs:manifest`.
 *
 * Typed element interfaces for every registered custom element, plus the
 * global `HTMLElementTagNameMap` augmentation that makes
 * `document.createElement('c-button')` and `querySelector('c-button')`
 * return the typed element.
 */

import type { CAutocompleteFilter, CAutocompleteItem } from './components/c-autocomplete/CAutocomplete.vue';
import type { CButtonGroupValue } from './components/c-button-group/CButtonGroup.vue';
import type { CDataTableCellContent, CDataTableColumn, CDataTableExpandedContext, CDataTableRow, CDataTableSort, CDataTableTexts } from './components/c-data-table/CDataTable.vue';
import type { CPaginationOptions } from './components/c-pagination/CPagination.vue';
import type { CSelectItem, CToastMessage } from './types';

// Local (non-exported) types referenced by the interfaces, inlined.
type AccordionPrimitive = number | string;

type AccordionValue = AccordionPrimitive | AccordionPrimitive[] | null;

type DropdownItem = {
  disabled?: boolean;
  name: string;
  outerHTML?: string;
  querySelector?: (s: string) => Element | null;
  selected?: boolean;
  value: number | string;
};

interface RadioItem {
  disabled?: boolean;
  name: string;
  value: number | string;
}

/** Events dispatched by `<c-accordion>`. */
export interface CAccordionElementEventMap {
  /**
   * Fired when the expansion state changes, carrying the new value as a bare
   * `detail`: the expanded item's value, an array of values in `multiple`
   * mode, or `null` when everything is collapsed.
   */
  change: CustomEvent<AccordionValue>;
  /**
   * Legacy value-change event carrying the new expansion value (kept for
   * existing `@changeValue` listeners and the `v-control` directive).
   */
  changeValue: CustomEvent<AccordionValue>;
  /**
   * Native bubbling input event dispatched alongside `changeValue` so a plain
   * `v-model` works without `v-control`; carries no detail.
   */
  input: CustomEvent<void>;
  /**
   * Fired with the new expansion value whenever an item is toggled — the
   * `v-model` contract.
   */
  'update:value': CustomEvent<AccordionValue>;
}

export interface CAccordionElement extends Omit<HTMLElement, 'mandatory' | 'multiple' | 'outlined' | 'value'> {
  /** Disallow collapsing all the items */
  mandatory?: boolean;
  /** Allow expanding multiple items */
  multiple?: boolean;
  /** Show an outline around expanded items */
  outlined?: boolean;
  /** Value of the accordion */
  value?: AccordionValue;
  addEventListener<K extends keyof CAccordionElementEventMap>(
    type: K,
    listener: (this: CAccordionElement, ev: CAccordionElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CAccordionElementEventMap>(
    type: K,
    listener: (this: CAccordionElement, ev: CAccordionElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Events dispatched by `<c-accordion-item>`. */
export interface CAccordionItemElementEventMap {
  /**
   * Fired when the header is toggled, carrying the requested expansion state
   * and the item's `value`; bubbles so the parent `<c-accordion>` can update
   * its model.
   */
  'item-change': CustomEvent<{ expanded: boolean; value: number | string | undefined }>;
}

export interface CAccordionItemElement extends Omit<HTMLElement, 'collapsable' | 'expanded' | 'heading' | 'outlined' | 'value'> {
  /** Marks the item as collapsable */
  collapsable?: boolean;
  /** Expansion status of the item */
  expanded?: boolean;
  /** Heading of the accordion item */
  heading?: string;
  /** Show an outline around the expanded item */
  outlined?: boolean;
  /** Value of the accordion item */
  value?: number | string;
  addEventListener<K extends keyof CAccordionItemElementEventMap>(
    type: K,
    listener: (this: CAccordionItemElement, ev: CAccordionItemElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CAccordionItemElementEventMap>(
    type: K,
    listener: (this: CAccordionItemElement, ev: CAccordionItemElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CAlertElement extends Omit<HTMLElement, 'type'> {
  /** Type of the alert */
  type?: 'default' | 'error' | 'info' | 'success' | 'warning';
}

/** Events dispatched by `<c-autocomplete>`. */
export interface CAutocompleteElementEventMap {
  /**
   * Native change event (no detail) dispatched whenever a selection is
   * committed or cleared; bubbles through the shadow boundary for
   * form-style listeners.
   */
  change: CustomEvent<void>;
  /**
   * Fired when the selected value changes (an option is committed or the
   * selection is cleared), carrying the new value — the option's value, or
   * the whole `{ name, value }` item when `return-object` is set; `null`
   * when cleared.
   */
  changeValue: CustomEvent<CAutocompleteItem | null | number | string>;
  /**
   * Native bubbling input event dispatched alongside every value change so a
   * plain `v-model` stays in sync. Carries no detail.
   */
  input: CustomEvent<void>;
  /**
   * Fired alongside `changeValue` with the same detail — the `v-model`
   * contract.
   */
  'update:value': CustomEvent<CAutocompleteItem | null | number | string>;
}

/** A filterable value-selection component: a readonly value field that opens a popover panel with a search input above the matching options. */
export interface CAutocompleteElement extends Omit<HTMLElement, 'clearable' | 'disabled' | 'errorMessage' | 'filter' | 'hideDetails' | 'hint' | 'hostId' | 'items' | 'itemsPerPage' | 'label' | 'labelOnTop' | 'loading' | 'name' | 'noResultsText' | 'placeholder' | 'required' | 'returnObject' | 'shadow' | 'valid' | 'value'> {
  /** Make the selected value clearable */
  clearable?: boolean;
  /** Disable the input */
  disabled?: boolean;
  /** Error message shown in place of the hint while the autocomplete is invalid */
  errorMessage?: string;
  /** Custom filter predicate; receives a normalized option + the query */
  filter?: CAutocompleteFilter;
  /** Hide the hint and error messages */
  hideDetails?: boolean;
  /** Hint text for the input */
  hint?: string;
  /** Id of the element */
  hostId?: string;
  /** Dropdown items (when not using <c-option> elements) */
  items?: CAutocompleteItem[];
  /** Items per page before the list scrolls */
  itemsPerPage?: number;
  /** Element label */
  label?: string;
  /** Label on top of the input */
  labelOnTop?: boolean;
  /** Show loading state */
  loading?: boolean;
  /** Input field name */
  name?: string;
  /** Message shown when the query matches no options */
  noResultsText?: string;
  /** Placeholder for the in-panel search input */
  placeholder?: string;
  /** Set the autocomplete as required */
  required?: boolean;
  /** Return object instead of value */
  returnObject?: boolean;
  /** Shadow variant */
  shadow?: boolean;
  /** Set the validity of the input */
  valid?: boolean;
  /** Selected value (scalar, or object when return-object is set) */
  value?: CAutocompleteItem | null | number | string;
  /** Reset autocomplete state */
  reset(): void;
  addEventListener<K extends keyof CAutocompleteElementEventMap>(
    type: K,
    listener: (this: CAutocompleteElement, ev: CAutocompleteElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CAutocompleteElementEventMap>(
    type: K,
    listener: (this: CAutocompleteElement, ev: CAutocompleteElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CBadgeElement extends HTMLElement {
}

/** Buttons trigger actions — submitting a form, opening a modal, confirming a choice. Use one primary (default appearance) button per view; secondary actions use the `outlined`, `ghost` or `text` appearances. */
export interface CButtonElement extends Omit<HTMLElement, 'active' | 'danger' | 'disabled' | 'fit' | 'ghost' | 'hostId' | 'href' | 'inverted' | 'loading' | 'noRadius' | 'noRipple' | 'outlined' | 'size' | 'target' | 'text' | 'type' | 'value'> {
  /**
   * Pressed (toggle) state — renders the selected look and sets
   * `aria-pressed`. Leave unset for regular action buttons: only a
   * true/false value marks the button as a toggle. Driven by
   * `c-button-group` on its slotted buttons.
   */
  active?: boolean;
  /** Danger variant style */
  danger?: boolean;
  /** Disable the button */
  disabled?: boolean;
  /** Fit width to containing element */
  fit?: boolean;
  /** Light button background */
  ghost?: boolean;
  /** Id of the button */
  hostId?: string;
  /** Hyperlink url */
  href?: string;
  /** Inverted button style for dark backgrounds */
  inverted?: boolean;
  /** Display loader on the button */
  loading?: boolean;
  /** Remove the default border radius */
  noRadius?: boolean;
  /** Suppress the click ripple (e.g. when a wrapper owns the press feedback). */
  noRipple?: boolean;
  /** Outlined button style */
  outlined?: boolean;
  /** Size of the button */
  size?: 'default' | 'large' | 'small';
  /** Hyperlink target */
  target?: string;
  /** Transparent button background */
  text?: boolean;
  /** Button type */
  type?: 'button' | 'reset' | 'submit';
  /**
   * Value for the button
   * - for use in the c-button-group
   */
  value?: number | string;
}

/** Events dispatched by `<c-button-group>`. */
export interface CButtonGroupElementEventMap {
  /**
   * Fired when the user changes the selection, carrying the new value:
   * the activated button's value (or index), `null` when the active button
   * is toggled off, or the array of active values in `multiple` mode.
   */
  change: CustomEvent<CButtonGroupValue>;
  /** Native bubbling input event dispatched for plain `v-model` support; carries no detail. */
  input: CustomEvent<void>;
  /**
   * Fired alongside `change` with the new selection; fulfills the `v-model`
   * contract.
   */
  'update:value': CustomEvent<CButtonGroupValue>;
}

/** A button group is a segmented control: a compact group of choices rendered as plain `c-button` children, where activating a button takes effect immediately (switching a view, picking a billing period). Selection is exclusive by default; set `multiple` to let several buttons be active at once. Give the group a `label` when it acts as a form field so the choice it represents is named for every user. */
export interface CButtonGroupElement extends Omit<HTMLElement, 'disabled' | 'label' | 'mandatory' | 'multiple' | 'required' | 'size' | 'value'> {
  /** Disable the whole group — every slotted c-button is disabled and the selection can no longer be changed. */
  disabled?: boolean;
  /** Label of the button group, shown above the buttons */
  label?: string;
  /**
   * The selection can never become empty: the active button (or, with
   * `multiple`, the last active button) cannot be toggled off. Distinct from
   * `required`: mandatory is a selection-behavior rule on the control, not a
   * form-level demand for an answer.
   */
  mandatory?: boolean;
  /**
   * Allow several buttons to be active at once. The value becomes an array
   * of the active buttons' values (in DOM order). Arrays have no attribute
   * form — bind `value` as a DOM property (`:value.prop` in Vue).
   */
  multiple?: boolean;
  /** Set as required — shows the required marker on the label */
  required?: boolean;
  /** Size of the buttons */
  size?: 'default' | 'small';
  /**
   * Value of the group: the active button's `value` (or its index when no
   * button declares one). `null` when nothing is selected. With `multiple`,
   * an array of the active buttons' values.
   */
  value?: CButtonGroupValue;
  addEventListener<K extends keyof CButtonGroupElementEventMap>(
    type: K,
    listener: (this: CButtonGroupElement, ev: CButtonGroupElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CButtonGroupElementEventMap>(
    type: K,
    listener: (this: CButtonGroupElement, ev: CButtonGroupElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CCardElement extends Omit<HTMLElement, 'fullscreen'> {
  /** Enable the fullscreen toggle button */
  fullscreen?: boolean;
  /** Enter fullscreen from the outside */
  enterFullscreen(): void;
  /** Exit fullscreen from the outside */
  exitFullscreen(): void;
}

export interface CCardActionsElement extends Omit<HTMLElement, 'align' | 'justify'> {
  /** Align the actions */
  align?: 'center' | 'end' | 'start';
  /** Justify the actions */
  justify?: 'center' | 'end' | 'space-around' | 'space-between' | 'start' | 'stretch';
}

export interface CCardContentElement extends HTMLElement {
}

export interface CCardTitleElement extends HTMLElement {
}

/** Events dispatched by `<c-checkbox>`. */
export interface CCheckboxElementEventMap {
  /**
   * Standard bubbling DOM change event, re-dispatched from the host when the
   * checkbox is toggled (the inner input's change does not cross the shadow
   * boundary). No detail; read the new value from the host's `value` property.
   */
  change: CustomEvent<void>;
  /**
   * Fired when the checkbox is toggled, carrying the new value —
   * `trueValue` when checked, `falseValue` when unchecked.
   */
  changeValue: CustomEvent<boolean | number | string>;
  /**
   * Native bubbling input event fired on toggle so a plain Vue `v-model`
   * works without the `v-control` directive. No detail.
   */
  input: CustomEvent<void>;
  /**
   * v-model contract event fired on toggle, carrying the new value —
   * `trueValue` when checked, `falseValue` when unchecked.
   */
  'update:value': CustomEvent<boolean | number | string>;
}

export interface CCheckboxElement extends Omit<HTMLElement, 'checked' | 'disabled' | 'errorMessage' | 'falseValue' | 'hideDetails' | 'hint' | 'hostId' | 'hostName' | 'indeterminate' | 'label' | 'required' | 'trueValue' | 'valid' | 'value'> {
  /** If `true`, the checkbox is selected. */
  checked?: boolean;
  /** Disable the checkbox */
  disabled?: boolean;
  /** Error message shown in place of the hint while the checkbox is invalid */
  errorMessage?: string;
  /** The value when the checkbox is unchecked */
  falseValue?: boolean | number | string;
  /** Hide the hint and error messages */
  hideDetails?: boolean;
  /** Hint text for the input */
  hint?: string;
  /** Id of the element */
  hostId?: string;
  /**
   * Name of the input
   * - Only used when the checkbox participates in a native `<form>`
   */
  hostName?: string;
  /** Indeterminate state */
  indeterminate?: boolean;
  /** Element label */
  label?: string;
  /** Set as required */
  required?: boolean;
  /** The value when the checkbox is checked */
  trueValue?: boolean | number | string;
  /** Set the validity of the input */
  valid?: boolean;
  /**
   * The input value
   * - Only used when the checkbox participates in a native `<form>`
   */
  value?: boolean | number | string;
  addEventListener<K extends keyof CCheckboxElementEventMap>(
    type: K,
    listener: (this: CCheckboxElement, ev: CCheckboxElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CCheckboxElementEventMap>(
    type: K,
    listener: (this: CCheckboxElement, ev: CCheckboxElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CCscLogoElement extends Omit<HTMLElement, 'width'> {
  /** Logo width in pixels */
  width?: number;
}

/** Events dispatched by `<c-data-table>`. */
export interface CDataTableElementEventMap {
  /** Fired when the expanded rows change, carrying the expanded row ids. */
  'change:expanded': CustomEvent<string[]>;
  /** Fired when the user changes the page, carrying the new 1-based page. */
  'change:page': CustomEvent<number>;
  /**
   * Fired when the user picks a new page size. Also resets the page to 1
   * (a separate `change:page` event fires alongside).
   */
  'change:page-size': CustomEvent<number>;
  /**
   * Fired when the selection changes, carrying the selected row ids and the
   * row objects resolvable from the current `data`.
   */
  'change:selected': CustomEvent<{ ids: string[]; rows: CDataTableRow[] }>;
  /** Fired when the user sorts a column, carrying the new sorting state. */
  'change:sort': CustomEvent<CDataTableSort | null>;
}

export interface CDataTableElement extends Omit<HTMLElement, 'autohide' | 'columns' | 'data' | 'expanded' | 'expandedContent' | 'external' | 'filter' | 'getRowId' | 'itemCount' | 'loading' | 'page' | 'pageSize' | 'pageSizes' | 'selected' | 'selection' | 'singleExpansion' | 'sort' | 'stickyFooter' | 'stickyHeader' | 'texts'> {
  /**
   * Move overflowing `expansion: 'auto'` columns into the expansion row
   * (rightmost first) instead of scrolling horizontally.
   */
  autohide?: boolean;
  /** Column definitions. Pass as a DOM property (contains functions). */
  columns?: CDataTableColumn[];
  /** Rows — plain domain objects. Pass as a DOM property. */
  data?: CDataTableRow[];
  /** Ids of the expanded rows (optionally controlled). */
  expanded?: string[];
  /**
   * Custom expansion-row content, appended after the auto-rendered cells of
   * columns currently in the expansion row.
   */
  expandedContent?: ( context: CDataTableExpandedContext, ) => CDataTableCellContent;
  /**
   * The server owns sorting, pagination and filtering: the table renders
   * `data` verbatim and only emits the state-change events. Requires
   * `itemCount` for the pager; disables the select-all banner and `filter`.
   */
  external?: boolean;
  /**
   * Filter rows client-side against this string (all columns). Ignored when
   * `external` is set.
   */
  filter?: string;
  /**
   * Return a stable id for a row. Falls back to the row's index — supply
   * this whenever selection/expansion is used with `external` data.
   */
  getRowId?: (row: CDataTableRow) => string;
  /** Total number of rows in the dataset. Only used (and needed) with `external`. */
  itemCount?: number;
  /** Show the loading indicator. */
  loading?: boolean;
  /** Current page, 1-based (optionally controlled). */
  page?: number;
  /**
   * Rows per page. Pagination is active only when set — without it every row
   * renders and no pager is shown.
   */
  pageSize?: number;
  /** Options for the pager's page-size menu. */
  pageSizes?: number[];
  /** Ids of the selected rows (optionally controlled). */
  selected?: string[];
  /** Row selection mode. Unset means rows are not selectable. */
  selection?: 'multiple' | 'single';
  /** Allow only one row to be expanded at a time. */
  singleExpansion?: boolean;
  /** The sorting state (optionally controlled). `null` renders unsorted. */
  sort?: CDataTableSort | null;
  /** Keep the footer row visible while the table scrolls vertically. */
  stickyFooter?: boolean;
  /** Keep the header row visible while the table scrolls vertically. */
  stickyHeader?: boolean;
  /** UI text overrides (i18n), merged over the English defaults. */
  texts?: CDataTableTexts;
  addEventListener<K extends keyof CDataTableElementEventMap>(
    type: K,
    listener: (this: CDataTableElement, ev: CDataTableElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CDataTableElementEventMap>(
    type: K,
    listener: (this: CDataTableElement, ev: CDataTableElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CDividerElement extends Omit<HTMLElement, 'vertical'> {
  /** Render a vertical separator instead of the default horizontal one. */
  vertical?: boolean;
}

/** Events dispatched by `<c-dropdown>`. */
export interface CDropdownElementEventMap {
  /**
   * Fired when the dropdown menu opens or closes; the detail is the new open
   * state.
   */
  dropdownStateChange: CustomEvent<boolean>;
  /**
   * Fired when the user selects an option row, carrying the option's name
   * and value for the parent (c-select) to commit.
   */
  selectOption: CustomEvent<{ name: string; value: number | string }>;
}

export interface CDropdownElement extends Omit<HTMLElement, 'dropdownItemType' | 'hostId' | 'index' | 'items' | 'itemsPerPage' | 'parent' | 'type'> {
  /** Whether items are <c-option> elements or plain objects */
  dropdownItemType?: 'item' | 'option';
  /** Id used to build option/announce element ids */
  hostId?: string;
  /** Current highlighted index */
  index?: null | number;
  /** Dropdown options: a NodeList of <c-option> or an array of items */
  items?: ArrayLike<DropdownItem>;
  /** Items per page before adding scroll */
  itemsPerPage?: number;
  /** Dropdown parent (the c-select / c-autocomplete host element) */
  parent?: HTMLElement | null;
  /** Parent type — drives autocomplete-only behaviour (highlight, messages) */
  type?: 'autocomplete' | 'select';
  /** Close dropdown */
  close(): void;
  focusItem(index: number): void;
  /** Open dropdown */
  open(): void;
  /** Select item */
  selectItem(index: number): void;
  setStatusText(text: string): void;
  /** Update list items */
  updateList(reset?: boolean): void;
  addEventListener<K extends keyof CDropdownElementEventMap>(
    type: K,
    listener: (this: CDropdownElement, ev: CDropdownElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CDropdownElementEventMap>(
    type: K,
    listener: (this: CDropdownElement, ev: CDropdownElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CIconElement extends Omit<HTMLElement, 'color' | 'path' | 'size'> {
  /** Fill color. */
  color?: string;
  /** Svg `path` `d` attribute value. */
  path: string;
  /** Icon size in pixels. */
  size?: number;
}

export interface CIconButtonElement extends Omit<HTMLElement, 'badge' | 'danger' | 'disabled' | 'ghost' | 'inverted' | 'loading' | 'outlined' | 'path' | 'size' | 'text'> {
  /** Show a badge on top of the icon */
  badge?: null | number | string;
  /** Danger variant of the button */
  danger?: boolean;
  /** Disable the button */
  disabled?: boolean;
  /** Ghost variant of the button */
  ghost?: boolean;
  /** Inverted color for dark backgrounds */
  inverted?: boolean;
  /** Loading variant of the button */
  loading?: boolean;
  /** Outlined variant of the button */
  outlined?: boolean;
  /** Path for the svg icon */
  path?: string;
  /** Size of the button */
  size?: 'default' | 'small' | 'x-small';
  /** Text variant of the button */
  text?: boolean;
}

export interface CInputElement extends Omit<HTMLElement, 'active' | 'disabled' | 'errorMessage' | 'filled' | 'hideDetails' | 'hint' | 'inputId' | 'isTextarea' | 'label' | 'labelOnTop' | 'required' | 'shadow' | 'valid'> {
  /** Set by the wrapping form component when its input has focus or holds a value. */
  active?: boolean;
  /** Disable the input */
  disabled?: boolean;
  /** Error message shown in place of the hint while the input is invalid */
  errorMessage?: string;
  /** Set by the wrapping form component when its input holds a value. */
  filled?: boolean;
  /** Hide the hint and error messages */
  hideDetails?: boolean;
  /** Hint text for the input */
  hint?: string;
  /** id of the inner input element (for the label's htmlFor). */
  inputId?: string;
  /** Renders textarea-specific spacing tweaks. */
  isTextarea?: boolean;
  /** Label of the input */
  label?: string;
  /** Label on top of the input */
  labelOnTop?: boolean;
  /** Set the input as required */
  required?: boolean;
  /** Shadow variant of the input */
  shadow?: boolean;
  /** Set the validíty of the input */
  valid?: boolean;
}

/** Basic hyperlink component */
export interface CLinkElement extends Omit<HTMLElement, 'href' | 'target' | 'underline' | 'weight'> {
  /** Url of link */
  href?: string;
  /** regular target attribute of a hyperlink */
  target?: string;
  /** Display line under the link */
  underline?: boolean;
  /** Customisable font weight */
  weight?: number | string;
}

export interface CListElement extends Omit<HTMLElement, 'bordered' | 'disabled'> {
  /** Show border arount the list items */
  bordered?: boolean;
  /** Disable the list */
  disabled?: boolean;
}

export interface CListItemElement extends Omit<HTMLElement, 'active' | 'disabled' | 'disabledByParent' | 'hoverable' | 'href' | 'ripple' | 'target'> {
  /** Set the item active */
  active?: boolean;
  /** Disable the item */
  disabled?: boolean;
  /** Disabled by the parent list */
  disabledByParent?: boolean;
  /** Display background color on hover */
  hoverable?: boolean;
  /** Hyperlink url */
  href?: string;
  /** Add ripple effect to the item */
  ripple?: boolean;
  /** Hyperlink target */
  target?: string;
}

export interface CListItemTitleElement extends Omit<HTMLElement, 'active'> {
  /** Set the title active */
  active?: boolean;
}

/** A loader component that fills the nearest containing element that has css-property position set to 'relative' */
export interface CLoaderElement extends Omit<HTMLElement, 'contentdelay' | 'size' | 'visible' | 'width'> {
  /** Delay in seconds of showing the contents in the slot of the loader */
  contentdelay?: number;
  /** Size of the loader */
  size?: number;
  /**
   * Whether the loader is shown. Toggling this drives the fade-in / smooth
   * fade-out — keep the element mounted and bind `visible` rather than using
   * `v-if`, which would unmount it and skip the leave transition.
   *
   * For imperative control (non-Vue consumers holding an element ref) the
   * element also exposes `show()` / `hide()` methods. The prop is named
   * `visible` (not `show`) so it doesn't collide with the `show()` method —
   * mirroring native `<dialog>` (`open` property + `show()`/`close()` methods).
   *
   * NOTE: this replaces the original Stencil `hide` prop with its inverse, so
   * the default (`true` = shown) preserves the original default behaviour.
   */
  visible?: boolean;
  /** Width of the loader */
  width?: number;
  /** Imperatively hide the loader (plays the smooth fade-out). */
  hide(): void;
  /** Imperatively show the loader (plays the fade-in). */
  show(): void;
}

export interface CLoginButtonElement extends Omit<HTMLElement, 'alt' | 'href' | 'src'> {
  /** Alt description for logo */
  alt?: string;
  /** Login provider link. Do not set if using a javascript click handler */
  href?: string;
  /** Login provider logo url */
  src?: string;
}

export interface CLoginButtonsElement extends HTMLElement {
}

export interface CLoginCardElement extends Omit<HTMLElement, 'backgroundPosition' | 'mobileBreakpoint' | 'overlay' | 'overlayBlendMode' | 'src'> {
  /** Background position (css background-position) */
  backgroundPosition?: string;
  /** Mobile breakpoint in pixels */
  mobileBreakpoint?: number;
  /** Add colored overlay to the background image */
  overlay?: boolean;
  /** Add colored overlay to the background image */
  overlayBlendMode?: 'color-burn' | 'color-dodge' | 'color' | 'darken' | 'difference' | 'exclusion' | 'hard-light' | 'hue' | 'lighten' | 'luminosity' | 'multiply' | 'normal' | 'overlay' | 'saturation' | 'screen' | 'soft-light';
  /** Background image */
  src?: string;
}

export interface CLoginCardActionsElement extends Omit<HTMLElement, 'align' | 'justify'> {
  /** Align the actions */
  align?: 'center' | 'end' | 'start';
  /** Justify the actions */
  justify?: 'center' | 'end' | 'space-around' | 'space-between' | 'start' | 'stretch';
}

export interface CLoginCardContentElement extends HTMLElement {
}

export interface CLoginCardTitleElement extends HTMLElement {
}

/** Wrapper component for the whole page */
export interface CMainElement extends Omit<HTMLElement, 'disableLayout'> {
  /** Disable the default dashboard layout */
  disableLayout?: boolean;
}

/** Events dispatched by `<c-menu>`. */
export interface CMenuElementEventMap {
  /**
   * Fired whenever the menu opens or closes, carrying the new open state.
   * Named `change:open`, not `update:open`: Vue's runtime silently drops
   * `onUpdate:*` listeners on custom elements (`isModelListener`), so a
   * template `@update:open` would never be attached.
   */
  'change:open': CustomEvent<boolean>;
  /**
   * Fired when a leaf menu item is selected, carrying the item's `value`;
   * bubbles out of the menu so a single listener can handle the whole tree.
   */
  select: CustomEvent<{ value: unknown }>;
}

export interface CMenuElement extends Omit<HTMLElement, 'distance' | 'open' | 'position'> {
  /** Distance from the trigger to the panel, in pixels. Defaults to `0`. */
  distance?: number | string;
  /** Whether the menu is open. Two-way: emits `change:open`. */
  open?: boolean;
  /** Preferred placement of the panel relative to the trigger. */
  position?: 'bottom-end' | 'bottom-start' | 'bottom' | 'left-end' | 'left-start' | 'left' | 'right-end' | 'right-start' | 'right' | 'top-end' | 'top-start' | 'top';
  addEventListener<K extends keyof CMenuElementEventMap>(
    type: K,
    listener: (this: CMenuElement, ev: CMenuElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CMenuElementEventMap>(
    type: K,
    listener: (this: CMenuElement, ev: CMenuElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** A single command in a `c-menu`. */
export interface CMenuItemElement extends Omit<HTMLElement, 'danger' | 'disabled' | 'value'> {
  /** Marks the action as destructive (renders in the error colour). */
  danger?: boolean;
  /** Disables the item — it is skipped by keyboard nav and emits no select. */
  disabled?: boolean;
  /** Value reported in the menu's `select` event when this item is chosen. */
  value?: string;
  closeSubmenu(): void;
  openSubmenu(): void;
}

/** Section label for a group of `c-menu-item`s. */
export interface CMenuLabelElement extends HTMLElement {
}

export interface CMessageElement extends Omit<HTMLElement, 'errorMessage' | 'hint' | 'inputId' | 'valid'> {
  /** Error message shown in place of the hint while the parent is invalid */
  errorMessage?: string;
  /** Hint text for the input */
  hint?: string;
  /** Id of the related input element */
  inputId?: string;
  /** Parent validíty */
  valid?: boolean;
}

/** Events dispatched by `<c-modal>`. */
export interface CModalElementEventMap {
  /**
   * Fired when the modal dismisses itself — a backdrop click or the Escape
   * key on a `dismissable` modal, or a platform-initiated close (e.g. a
   * slotted `<form method="dialog">`). The detail is the new open state,
   * always `false`.
   */
  changeValue: CustomEvent<boolean>;
  /**
   * Native bubbling input event dispatched alongside every value change so a
   * plain `v-model` stays in sync. Carries no detail.
   */
  input: CustomEvent<void>;
  /**
   * Fired alongside `changeValue` with the same detail — the `v-model`
   * contract.
   */
  'update:value': CustomEvent<boolean>;
}

/** Modals interrupt the page for a task that must be completed (or explicitly cancelled) before continuing — confirmations, short forms, destructive-action warnings. The slotted content is typically a `c-card`. */
export interface CModalElement extends Omit<HTMLElement, 'disableBackdropBlur' | 'dismissable' | 'value' | 'width'> {
  /** Disable backdrop blur effect */
  disableBackdropBlur?: boolean;
  /**
   * Dismissed when touching/clicking outside the content or pressing Escape.
   * A non-dismissable modal responds to either gesture with a nudge animation
   * instead of closing.
   */
  dismissable?: boolean;
  /** Is the modal visible */
  value?: boolean;
  /** Width of the dialog. Numeric value is considered as pixel value (400 -> 400px) */
  width?: number | string;
  addEventListener<K extends keyof CModalElementEventMap>(
    type: K,
    listener: (this: CModalElement, ev: CModalElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CModalElementEventMap>(
    type: K,
    listener: (this: CModalElement, ev: CModalElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CNavigationButtonElement extends HTMLElement {
}

export interface COptionElement extends Omit<HTMLElement, 'disabled' | 'name' | 'selected' | 'value'> {
  /** Set option as disabled */
  disabled?: boolean;
  /** Option name (display label fallback) */
  name?: string;
  /** Set option as selected */
  selected?: boolean;
  /** Option value */
  value?: number | string;
}

export interface COptionValueElement extends HTMLElement {
}

/** Events dispatched by `<c-otp-input>`. */
export interface COtpInputElementEventMap {
  /**
   * Fired on every digit change with the complete code once all digits are
   * filled, or `null` while the code is still incomplete (legacy value-change
   * event).
   */
  changeValue: CustomEvent<null | string>;
  /** Fired when the last digit is filled, carrying the complete code. */
  completion: CustomEvent<null | string>;
  /**
   * Native bubbling input event for plain `v-model`; carries no detail — the
   * model value is mirrored onto the host's `value` property.
   */
  input: CustomEvent<void>;
  /**
   * Fired on every digit change with the currently entered digits (v-model
   * contract).
   */
  'update:value': CustomEvent<string>;
}

export interface COtpInputElement extends Omit<HTMLElement, 'elementId' | 'errorMessage' | 'hasAutofocus' | 'hideDetails' | 'hint' | 'label' | 'length' | 'required' | 'valid' | 'value'> {
  /** Id of the element */
  elementId?: string;
  /** Error message shown in place of the hint while the input is invalid */
  errorMessage?: string;
  /** Auto focus */
  hasAutofocus?: boolean;
  /** Hide the hint and error messages */
  hideDetails?: boolean;
  /** Hint text for the input */
  hint?: string;
  /** Label of the input group, shown above the digit inputs */
  label?: string;
  /** Length of the OTP code */
  length?: number;
  /** Set as required — shows the required marker on the label */
  required?: boolean;
  /** Set the validíty of the input */
  valid?: boolean;
  /** Value of the input */
  value?: string;
  addEventListener<K extends keyof COtpInputElementEventMap>(
    type: K,
    listener: (this: COtpInputElement, ev: COtpInputElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof COtpInputElementEventMap>(
    type: K,
    listener: (this: COtpInputElement, ev: COtpInputElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CPageElement extends Omit<HTMLElement, 'scrollIndicator'> {
  /** Display scroll indicator */
  scrollIndicator?: boolean;
}

/** Events dispatched by `<c-pagination>`. */
export interface CPaginationElementEventMap {
  /**
   * Fired when the user changes the page or the page size, carrying the
   * pagination options object with the recomputed `currentPage`,
   * `itemsPerPage`, `startFrom` and `endTo` fields.
   */
  changeValue: CustomEvent<CPaginationOptions>;
  /**
   * Native bubbling input event dispatched alongside every value change so a
   * plain `v-model` stays in sync. Carries no detail.
   */
  input: CustomEvent<void>;
  /**
   * Fired alongside `changeValue` with the same detail — the `v-model`
   * contract.
   */
  'update:value': CustomEvent<CPaginationOptions>;
}

export interface CPaginationElement extends Omit<HTMLElement, 'hideDetails' | 'hideRange' | 'simple' | 'size' | 'value'> {
  /** Hide details (per page dropdown and the 'x - y of n pages' text) */
  hideDetails?: boolean;
  /** Hide range indicator */
  hideRange?: boolean;
  /** Hide page number buttons */
  simple?: boolean;
  /** Hide details (per page dropdown and the 'x - y of n pages' text) */
  size?: 'default' | 'small';
  /**
   * Object containing values that are needed for pagination.
   *
   * Note! startFrom and endTo are assigned automatically to the object based on other values
   */
  value?: CPaginationOptions;
  addEventListener<K extends keyof CPaginationElementEventMap>(
    type: K,
    listener: (this: CPaginationElement, ev: CPaginationElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CPaginationElementEventMap>(
    type: K,
    listener: (this: CPaginationElement, ev: CPaginationElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CProgressBarElement extends Omit<HTMLElement, 'hideDetails' | 'indeterminate' | 'label' | 'singleLine' | 'value'> {
  /** Hide the percentage display */
  hideDetails?: boolean;
  /** Indeterminate state of the progress bar */
  indeterminate?: boolean;
  /** Optional details message next to percentage display */
  label?: string;
  /** Place details next to progress bar */
  singleLine?: boolean;
  /** Progress bar value in percentage (0 to 100) */
  value?: number;
}

export interface CRadioElement extends Omit<HTMLElement, 'checked' | 'disabled' | 'value'> {
  /** Set option as checked */
  checked?: boolean;
  /** Disable the radio button */
  disabled?: boolean;
  /** Radio button value */
  value?: string;
}

/** Events dispatched by `<c-radio-group>`. */
export interface CRadioGroupElementEventMap {
  /**
   * Fired when a radio option is selected, carrying the selected item's
   * value — or the whole item object when `return-object` is set.
   */
  changeValue: CustomEvent<number | RadioItem | string>;
  /**
   * Native bubbling input event fired on selection so a plain Vue `v-model`
   * works without the `v-control` directive. No detail.
   */
  input: CustomEvent<void>;
  /**
   * v-model contract event fired on selection, carrying the selected item's
   * value — or the whole item object when `return-object` is set.
   */
  'update:value': CustomEvent<number | RadioItem | string>;
}

export interface CRadioGroupElement extends Omit<HTMLElement, 'disabled' | 'errorMessage' | 'hideDetails' | 'hint' | 'hostId' | 'inline' | 'items' | 'label' | 'required' | 'returnObject' | 'valid' | 'value'> {
  /** Disable the radio group */
  disabled?: boolean;
  /** Error message shown in place of the hint while the group is invalid */
  errorMessage?: string;
  /** Hide the hint and error messages */
  hideDetails?: boolean;
  /** Hint text for the input */
  hint?: string;
  /** Id of the element */
  hostId?: string;
  /** Display radio buttons inline */
  inline?: boolean;
  /** Radio group items */
  items?: RadioItem[];
  /** Label of the radio group */
  label?: string;
  /** Set as required */
  required?: boolean;
  /** Return the whole item object */
  returnObject?: boolean;
  /** Set the validity of the input */
  valid?: boolean;
  /** Value of the radio group */
  value?: null | number | RadioItem | string;
  addEventListener<K extends keyof CRadioGroupElementEventMap>(
    type: K,
    listener: (this: CRadioGroupElement, ev: CRadioGroupElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CRadioGroupElementEventMap>(
    type: K,
    listener: (this: CRadioGroupElement, ev: CRadioGroupElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Generic flex row component */
export interface CRowElement extends Omit<HTMLElement, 'align' | 'gap' | 'justify' | 'nowrap'> {
  /** Align items vertically */
  align?: 'center' | 'end' | 'start';
  /** Gap between items in px */
  gap?: number;
  /** Justify content horizontally */
  justify?: 'center' | 'end' | 'space-around' | 'space-between' | 'start';
  /** Disable flex wrap */
  nowrap?: boolean;
}

/** Events dispatched by `<c-select>`. */
export interface CSelectElementEventMap {
  /**
   * Fired when the selection changes (an option is picked or the value is
   * cleared), carrying the new value — the option's value, or the whole
   * `{ name, value }` item when `return-object` is set; `null` when cleared.
   */
  changeValue: CustomEvent<CSelectItem | null | number | string>;
  /**
   * Native bubbling input event dispatched alongside every value change so a
   * plain `v-model` stays in sync. Carries no detail.
   */
  input: CustomEvent<void>;
  /**
   * Fired alongside `changeValue` with the same detail — the `v-model`
   * contract.
   */
  'update:value': CustomEvent<CSelectItem | null | number | string>;
}

export interface CSelectElement extends Omit<HTMLElement, 'clearable' | 'disabled' | 'errorMessage' | 'hideDetails' | 'hint' | 'hostId' | 'items' | 'itemsPerPage' | 'label' | 'labelOnTop' | 'loading' | 'name' | 'optionAsSelection' | 'placeholder' | 'required' | 'returnObject' | 'shadow' | 'valid' | 'value'> {
  /** Make the selected value clearable */
  clearable?: boolean;
  /** Disable the input */
  disabled?: boolean;
  /** Error message shown in place of the hint while the select is invalid */
  errorMessage?: string;
  /** Hide the hint and error messages */
  hideDetails?: boolean;
  /** Hint text for the input */
  hint?: string;
  /** Id of the element */
  hostId?: string;
  /** Dropdown items (when not using <c-option> elements) */
  items?: CSelectItem[];
  /** Items per page before adding scroll */
  itemsPerPage?: number;
  /** Element label */
  label?: string;
  /** Label on top of the input */
  labelOnTop?: boolean;
  /** Show loading state */
  loading?: boolean;
  /** Input field name */
  name?: string;
  /** Display the option as selection (only with <c-option> elements) */
  optionAsSelection?: boolean;
  /** Placeholder text */
  placeholder?: string;
  /** Set the select as required */
  required?: boolean;
  /** Return object instead of value */
  returnObject?: boolean;
  /** Shadow variant */
  shadow?: boolean;
  /** Set the validity of the input */
  valid?: boolean;
  /** Selected value (scalar, or object when return-object is set) */
  value?: CSelectItem | null | number | string;
  /** Reset select state */
  reset(): void;
  addEventListener<K extends keyof CSelectElementEventMap>(
    type: K,
    listener: (this: CSelectElement, ev: CSelectElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CSelectElementEventMap>(
    type: K,
    listener: (this: CSelectElement, ev: CSelectElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Events dispatched by `<c-side-navigation>`. */
export interface CSideNavigationElementEventMap {
  /**
   * Fired when the drawer is closed from within (the mobile close button or
   * the backdrop overlay), carrying the new visibility (`false`).
   * Named `change:menu-visible`, not `update:menuVisible`: Vue's runtime
   * silently drops `onUpdate:*` listeners on custom elements
   * (`isModelListener`), so a template `@update:menu-visible` would never be
   * attached.
   */
  'change:menu-visible': CustomEvent<boolean>;
}

export interface CSideNavigationElement extends Omit<HTMLElement, 'menuVisible' | 'mobile' | 'styles'> {
  /** Mobile version menu visibility */
  menuVisible?: boolean;
  /** Mobile version */
  mobile?: boolean;
  /** Background styles */
  styles?: null | Record<string, string>;
  addEventListener<K extends keyof CSideNavigationElementEventMap>(
    type: K,
    listener: (this: CSideNavigationElement, ev: CSideNavigationElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CSideNavigationElementEventMap>(
    type: K,
    listener: (this: CSideNavigationElement, ev: CSideNavigationElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Events dispatched by `<c-side-navigation-item>`. */
export interface CSideNavigationItemElementEventMap {
  /**
   * Fired when the item is activated (click or Enter), carrying the
   * originating DOM event; bubbles so the parent `<c-side-navigation>` can
   * coordinate which item is active.
   */
  itemChange: CustomEvent<Event>;
}

export interface CSideNavigationItemElement extends Omit<HTMLElement, 'active' | 'focusable' | 'href' | 'loading' | 'target'> {
  /** Indicate active state */
  active?: boolean;
  /** Whether the item is in the keyboard tab order — a parent item sets this to false on its collapsed sub-items so hidden items aren't Tab-reachable */
  focusable?: boolean;
  /** Hyperlink url */
  href?: string;
  /** Loading state */
  loading?: boolean;
  /** Hyperlink target */
  target?: string;
  addEventListener<K extends keyof CSideNavigationItemElementEventMap>(
    type: K,
    listener: (this: CSideNavigationItemElement, ev: CSideNavigationItemElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CSideNavigationItemElementEventMap>(
    type: K,
    listener: (this: CSideNavigationItemElement, ev: CSideNavigationItemElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CSideNavigationTitleElement extends HTMLElement {
}

/** Events dispatched by `<c-slider>`. */
export interface CSliderElementEventMap {
  /**
   * Fired on every thumb movement, carrying the new slider value — a number
   * when the current `value` prop is a number, otherwise a string.
   */
  changeValue: CustomEvent<number | string>;
  /**
   * Native bubbling input event fired on every thumb movement so a plain Vue
   * `v-model` works without the `v-control` directive. No detail.
   */
  input: CustomEvent<void>;
  /**
   * v-model contract event fired on every thumb movement, carrying the new
   * slider value — a number when the current `value` prop is a number,
   * otherwise a string.
   */
  'update:value': CustomEvent<number | string>;
}

export interface CSliderElement extends Omit<HTMLElement, 'ariaLabelInternal' | 'disabled' | 'disableTooltip' | 'hostId' | 'hostName' | 'label' | 'labels' | 'max' | 'min' | 'segments' | 'step' | 'ticks' | 'unit' | 'value'> {
  /** Aria label */
  ariaLabelInternal?: string;
  /** Disable the slider */
  disabled?: boolean;
  /** Disable tooltip */
  disableTooltip?: boolean;
  /** Id of the element */
  hostId?: string;
  /** Id of the element */
  hostName?: string;
  /** Label of the slider */
  label?: string;
  /** Show tick labels */
  labels?: boolean;
  /** Max value */
  max?: number | string;
  /** Min value */
  min?: number | string;
  /** Segment count */
  segments?: number | string;
  /** Step */
  step?: number | string;
  /** Thow ticks */
  ticks?: boolean;
  /** Unit */
  unit?: string;
  /** Value */
  value?: number | string;
  addEventListener<K extends keyof CSliderElementEventMap>(
    type: K,
    listener: (this: CSliderElement, ev: CSliderElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CSliderElementEventMap>(
    type: K,
    listener: (this: CSliderElement, ev: CSliderElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Spacer component for flex containers */
export interface CSpacerElement extends HTMLElement {
}

export interface CSpinnerElement extends Omit<HTMLElement, 'color' | 'size' | 'width'> {
  /** Color of the spinner */
  color?: string;
  /** Size of the spinner */
  size?: number;
  /** Width of the spinner */
  width?: number;
}

export interface CStatusElement extends Omit<HTMLElement, 'type'> {
  /** Status type */
  type?: 'error' | 'info' | 'success' | 'warning';
}

export interface CStepElement extends Omit<HTMLElement, 'complete' | 'current'> {
  /** Mark step as complete */
  complete?: boolean;
  /** Mark step as current */
  current?: boolean;
}

export interface CStepsElement extends Omit<HTMLElement, 'value'> {
  /** Value of the accordion (current step number) */
  value?: number | string;
}

export interface CSubNavigationItemElement extends Omit<HTMLElement, 'active' | 'focusable' | 'href' | 'loading' | 'target'> {
  /** Active state */
  active?: boolean;
  /** Element is visible and focusable */
  focusable?: boolean;
  /** Link url */
  href?: string;
  /** Loading state */
  loading?: boolean;
  /** Link target */
  target?: string;
}

/** Events dispatched by `<c-swiper>`. */
export interface CSwiperElementEventMap {
  /**
   * Fired when a tab is selected via click or arrow-key navigation, carrying
   * the selected tab's value (legacy value-change event).
   */
  changeValue: CustomEvent<number | string>;
  /**
   * Native bubbling input event for plain `v-model`; carries no detail — the
   * selected value is mirrored onto the host's `value` property.
   */
  input: CustomEvent<void>;
  /**
   * Fired when a tab is selected via click or arrow-key navigation, carrying
   * the selected tab's value (v-model contract).
   */
  'update:value': CustomEvent<number | string>;
}

export interface CSwiperElement extends Omit<HTMLElement, 'elementId' | 'value'> {
  /** Id of the swiper element */
  elementId?: string;
  /** Value of the swiper */
  value?: number | string;
  addEventListener<K extends keyof CSwiperElementEventMap>(
    type: K,
    listener: (this: CSwiperElement, ev: CSwiperElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CSwiperElementEventMap>(
    type: K,
    listener: (this: CSwiperElement, ev: CSwiperElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Events dispatched by `<c-swiper-tab>`. */
export interface CSwiperTabElementEventMap {
  /**
   * Fired when an inactive, enabled tab is clicked, carrying the tab's value.
   * Bubbles up to the parent `<c-swiper>`, which uses it to select the tab.
   */
  changeValue: CustomEvent<number | string | undefined>;
}

export interface CSwiperTabElement extends Omit<HTMLElement, 'active' | 'disabled' | 'hostId' | 'label' | 'position' | 'setsize' | 'value'> {
  /** Mark as active */
  active?: boolean;
  /** Disable button */
  disabled?: boolean;
  /** Id of the button */
  hostId?: string;
  /** Label of the button */
  label?: string;
  /** Position in the set */
  position?: number;
  /** Size of the set */
  setsize?: number;
  /** Value of the button */
  value?: number | string;
  addEventListener<K extends keyof CSwiperTabElementEventMap>(
    type: K,
    listener: (this: CSwiperTabElement, ev: CSwiperTabElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CSwiperTabElementEventMap>(
    type: K,
    listener: (this: CSwiperTabElement, ev: CSwiperTabElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Events dispatched by `<c-switch>`. */
export interface CSwitchElementEventMap {
  /**
   * Standard bubbling DOM change event, re-dispatched from the host when the
   * switch is toggled (the inner input's change does not cross the shadow
   * boundary). No detail; read the new value from the host's `value` property.
   */
  change: CustomEvent<void>;
  /**
   * Fired when the switch is toggled, carrying the new value —
   * `trueValue` when on, `falseValue` when off.
   */
  changeValue: CustomEvent<boolean | number | string>;
  /**
   * Native bubbling input event fired on toggle so a plain Vue `v-model`
   * works without the `v-control` directive. No detail.
   */
  input: CustomEvent<void>;
  /**
   * v-model contract event fired on toggle, carrying the new value —
   * `trueValue` when on, `falseValue` when off.
   */
  'update:value': CustomEvent<boolean | number | string>;
}

export interface CSwitchElement extends Omit<HTMLElement, 'checked' | 'disabled' | 'falseValue' | 'hostId' | 'label' | 'loading' | 'required' | 'trueValue' | 'value'> {
  /** If `true`, the checkbox is selected. */
  checked?: boolean;
  /** If `true`, the switch is disabled and cannot be toggled */
  disabled?: boolean;
  /** The value when the checkbox is unchecked */
  falseValue?: boolean | number | string;
  /** Id for the element */
  hostId?: string;
  /**
   * Label of the switch, shown beside the toggle. Falls back to the default
   * slot content when not set.
   */
  label?: string;
  /** Loading state */
  loading?: boolean;
  /** Set as required */
  required?: boolean;
  /** The value when the checkbox is checked */
  trueValue?: boolean | number | string;
  /**
   * The input value
   * - Only used when the checkbox participates in a native `<form>`
   */
  value?: boolean | number | string;
  addEventListener<K extends keyof CSwitchElementEventMap>(
    type: K,
    listener: (this: CSwitchElement, ev: CSwitchElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CSwitchElementEventMap>(
    type: K,
    listener: (this: CSwitchElement, ev: CSwitchElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Events dispatched by `<c-tab>`. */
export interface CTabElementEventMap {
  /**
   * Fired when the tab is activated (click, or Space/Enter), carrying the tab
   * element and its value; the parent `<c-tabs>` listens for it to switch the
   * active tab.
   */
  tabChange: CustomEvent<{ element: HTMLElement | null; value: number | string | undefined; }>;
  /**
   * Fired when the tab receives focus, so the parent `<c-tabs>` can drive
   * arrow-key navigation.
   */
  tabFocus: CustomEvent<number | string | undefined>;
}

export interface CTabElement extends Omit<HTMLElement, 'active' | 'disabled' | 'hostId' | 'position' | 'setsize' | 'value'> {
  /** Mark tab as active */
  active?: boolean;
  /** Mark tab as disabled */
  disabled?: boolean;
  /** Id of the tab */
  hostId?: string;
  /** Position in the set */
  position?: number;
  /** Size of the set */
  setsize?: number;
  /**
   * Value for the tab
   * - for use in c-tabs
   */
  value?: number | string;
  addEventListener<K extends keyof CTabElementEventMap>(
    type: K,
    listener: (this: CTabElement, ev: CTabElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CTabElementEventMap>(
    type: K,
    listener: (this: CTabElement, ev: CTabElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Events dispatched by `<c-tab-buttons>`. */
export interface CTabButtonsElementEventMap {
  /**
   * Fired when the user activates a tab button, carrying the newly selected
   * value. The parent `<c-tabs>` listens for it and pushes the accepted value
   * back down; consumers should listen to `c-tabs` instead.
   */
  tabChange: CustomEvent<{ element: HTMLElement | null; value: number | string; }>;
}

/** Tab buttons present a `c-tabs` tab list as a segmented control instead of the underlined tab row. Author it only inside `<c-tabs>`, with plain `<c-button>` children whose `value`s match the `c-tab-item` panels; `c-tabs` owns the active value and pushes it down. */
export interface CTabButtonsElement extends Omit<HTMLElement, 'disabled' | 'size' | 'value'> {
  /** Disable the whole tab strip — every slotted c-button is disabled and the selection can no longer be changed. */
  disabled?: boolean;
  /** Size of the buttons */
  size?: 'default' | 'small';
  /** Value of the active tab — pushed down by the parent c-tabs. */
  value?: number | string;
  addEventListener<K extends keyof CTabButtonsElementEventMap>(
    type: K,
    listener: (this: CTabButtonsElement, ev: CTabButtonsElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CTabButtonsElementEventMap>(
    type: K,
    listener: (this: CTabButtonsElement, ev: CTabButtonsElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Events dispatched by `<c-tab-item>`. */
export interface CTabItemElementEventMap {
  /**
   * Fired whenever the panel's content is resized, so the parent
   * `<c-tab-items>` can re-measure and keep the slide position correct.
   */
  contentChange: CustomEvent<void>;
}

export interface CTabItemElement extends Omit<HTMLElement, 'active' | 'value'> {
  /** Active */
  active?: boolean;
  /** Tab value */
  value?: number | string;
  addEventListener<K extends keyof CTabItemElementEventMap>(
    type: K,
    listener: (this: CTabItemElement, ev: CTabItemElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CTabItemElementEventMap>(
    type: K,
    listener: (this: CTabItemElement, ev: CTabItemElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CTabItemsElement extends Omit<HTMLElement, 'disableAnimation' | 'value'> {
  /** Disable animation */
  disableAnimation?: boolean;
  /** Currently active tab */
  value?: number | string;
}

export interface CTableElement extends Omit<HTMLElement, 'mobileBreakpoint' | 'responsive'> {
  /** Mobile breakpoint in pixels */
  mobileBreakpoint?: number;
  /** Should the table be responsive */
  responsive?: boolean;
}

/** Events dispatched by `<c-tabs>`. */
export interface CTabsElementEventMap {
  /**
   * Fired when the user activates a tab (click, or Enter/Space on a focused
   * tab), carrying the newly selected tab value. Legacy value-change event.
   */
  changeValue: CustomEvent<number | string>;
  /** Native bubbling input event dispatched for plain `v-model` support; carries no detail. */
  input: CustomEvent<void>;
  /**
   * Fired alongside `changeValue` with the newly selected tab value; fulfills
   * the `v-model`/`v-control` contract.
   */
  'update:value': CustomEvent<number | string>;
}

export interface CTabsElement extends Omit<HTMLElement, 'borderless' | 'disableAnimation' | 'justify' | 'mobileBreakpoint' | 'value' | 'vertical'> {
  /** Disable the bottom border */
  borderless?: boolean;
  /** Disable animation */
  disableAnimation?: boolean;
  /** Justification of the children */
  justify?: 'center' | 'end' | 'start' | 'stretch';
  /**
   * Mobile breakpoint in pixels
   * - affects the content stacking with the vertical tabs
   */
  mobileBreakpoint?: number;
  /** Currently active tab */
  value?: number | string;
  /** Vertical tabs */
  vertical?: boolean;
  addEventListener<K extends keyof CTabsElementEventMap>(
    type: K,
    listener: (this: CTabsElement, ev: CTabsElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CTabsElementEventMap>(
    type: K,
    listener: (this: CTabsElement, ev: CTabsElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Events dispatched by `<c-tag>`. */
export interface CTagElementEventMap {
  /** Fired when the tag's close button is activated. */
  close: CustomEvent<void>;
}

export interface CTagElement extends Omit<HTMLElement, 'active' | 'badge' | 'closeable' | 'flat' | 'size'> {
  /** Mark tag as active */
  active?: boolean;
  /** Display an optional badge at the start of the tag */
  badge?: null | number | string;
  /** Mark tag as closeable */
  closeable?: boolean;
  /** Remove the hover effect */
  flat?: boolean;
  /** Size of the tag */
  size?: 'default' | 'small';
  addEventListener<K extends keyof CTagElementEventMap>(
    type: K,
    listener: (this: CTagElement, ev: CTagElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CTagElementEventMap>(
    type: K,
    listener: (this: CTagElement, ev: CTagElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

export interface CTagsElement extends Omit<HTMLElement, 'label' | 'required' | 'size'> {
  /** Label of the tag group, shown above the tags */
  label?: string;
  /** Set as required — shows the required marker on the label */
  required?: boolean;
  /** Size of the tags */
  size?: 'default' | 'small';
}

/** Events dispatched by `<c-text-field>`. */
export interface CTextFieldElementEventMap {
  /**
   * Standard bubbling DOM change event, re-dispatched from the host when the
   * inner input/textarea fires its native change (which does not cross the
   * shadow boundary). No detail; read the current text from the host's
   * `value` property.
   */
  change: CustomEvent<void>;
  /**
   * Fired on every keystroke (and on native change), carrying the current
   * text — trimmed when `trim-whitespace` is set.
   */
  changeValue: CustomEvent<string>;
  /**
   * Native bubbling input event fired alongside every value change so a
   * plain Vue `v-model` works without the `v-control` directive. No detail.
   */
  input: CustomEvent<void>;
  /**
   * v-model contract event fired on every keystroke (and on native change),
   * carrying the current text — trimmed when `trim-whitespace` is set.
   */
  'update:value': CustomEvent<string>;
}

export interface CTextFieldElement extends Omit<HTMLElement, 'autocomplete' | 'autocorrect' | 'automaticCapitalize' | 'disabled' | 'errorMessage' | 'hideDetails' | 'hint' | 'hostId' | 'label' | 'labelOnTop' | 'max' | 'min' | 'name' | 'placeholder' | 'readonly' | 'required' | 'rows' | 'shadow' | 'step' | 'trimWhitespace' | 'type' | 'valid' | 'value'> {
  /** HTML input autocomplete */
  autocomplete?: string;
  /**
   * Enable native input autocorrection (Safari). Maps to the input's
   * `autocorrect="on"`/`"off"` attribute; left unset (browser default per
   * input type) when not specified. Mirrors the platform
   * `HTMLElement.autocorrect` boolean.
   */
  autocorrect?: boolean;
  /** HTML input autocapitalize */
  automaticCapitalize?: 'characters' | 'none' | 'off' | 'on' | 'sentences' | 'words';
  /** Disable the input */
  disabled?: boolean;
  /** Error message shown in place of the hint while the input is invalid */
  errorMessage?: string;
  /** Hide the hint and error messages */
  hideDetails?: boolean;
  /** Hint text for the input */
  hint?: string;
  /** Id of the input */
  hostId?: string;
  /** Label of the input */
  label?: string;
  /** Label on top of the input */
  labelOnTop?: boolean;
  /** Maximum value on a numeric input */
  max?: null | number;
  /** Minimum value on a numeric input */
  min?: null | number;
  /** Name of the input */
  name?: string;
  /** Placeholder of the input */
  placeholder?: string;
  /** Mark as readonly */
  readonly?: boolean;
  /** Set the input as required */
  required?: boolean;
  /** Rows on the input */
  rows?: number;
  /** Shadow variant of the input */
  shadow?: boolean;
  /** Step size on a numeric input */
  step?: null | number;
  /** Trim whitespace from the return value */
  trimWhitespace?: boolean;
  /** Type of the input */
  type?: 'date' | 'email' | 'number' | 'password' | 'search' | 'tel' | 'text' | 'url';
  /** Set the validity of the input */
  valid?: boolean;
  /** Value of the input */
  value?: string;
  addEventListener<K extends keyof CTextFieldElementEventMap>(
    type: K,
    listener: (this: CTextFieldElement, ev: CTextFieldElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CTextFieldElementEventMap>(
    type: K,
    listener: (this: CTextFieldElement, ev: CTextFieldElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Events dispatched by `<c-toast>`. */
export interface CToastElementEventMap {
  /**
   * Fired once the toast's leave transition has finished (after a manual
   * dismiss or the auto-close timer), carrying the dismissed toast's message
   * object.
   */
  close: CustomEvent<CToastMessage | null>;
}

/** A single toast notification, rendered and managed by c-toasts */
export interface CToastElement extends Omit<HTMLElement, 'message'> {
  /** Messages */
  message?: CToastMessage | null;
  closeToast(): void;
  addEventListener<K extends keyof CToastElementEventMap>(
    type: K,
    listener: (this: CToastElement, ev: CToastElementEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | AddEventListenerOptions,
  ): void;
  removeEventListener<K extends keyof CToastElementEventMap>(
    type: K,
    listener: (this: CToastElement, ev: CToastElementEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject,
    options?: boolean | EventListenerOptions,
  ): void;
}

/** Toasts are passive, transient notifications — operation results, background progress — stacked and managed by a single `c-toasts` container via its `addToast` / `removeToast` methods. */
export interface CToastsElement extends Omit<HTMLElement, 'absolute' | 'horizontal' | 'vertical'> {
  /** Use absolute positioning */
  absolute?: boolean;
  /** Horizontal position */
  horizontal?: 'center' | 'left' | 'right';
  /** Vertical position */
  vertical?: 'bottom' | 'top';
  /** Add a new message */
  addToast(message: CToastMessage): void;
  /** Remove a message by id (id should be specified in the addToast params) */
  removeToast(id: string): void;
}

export interface CToolbarElement extends HTMLElement {
}

declare global {
  interface HTMLElementTagNameMap {
    'c-accordion': CAccordionElement;
    'c-accordion-item': CAccordionItemElement;
    'c-alert': CAlertElement;
    'c-autocomplete': CAutocompleteElement;
    'c-badge': CBadgeElement;
    'c-button': CButtonElement;
    'c-button-group': CButtonGroupElement;
    'c-card': CCardElement;
    'c-card-actions': CCardActionsElement;
    'c-card-content': CCardContentElement;
    'c-card-title': CCardTitleElement;
    'c-checkbox': CCheckboxElement;
    'c-csc-logo': CCscLogoElement;
    'c-data-table': CDataTableElement;
    'c-divider': CDividerElement;
    'c-dropdown': CDropdownElement;
    'c-icon': CIconElement;
    'c-icon-button': CIconButtonElement;
    'c-input': CInputElement;
    'c-link': CLinkElement;
    'c-list': CListElement;
    'c-list-item': CListItemElement;
    'c-list-item-title': CListItemTitleElement;
    'c-loader': CLoaderElement;
    'c-login-button': CLoginButtonElement;
    'c-login-buttons': CLoginButtonsElement;
    'c-login-card': CLoginCardElement;
    'c-login-card-actions': CLoginCardActionsElement;
    'c-login-card-content': CLoginCardContentElement;
    'c-login-card-title': CLoginCardTitleElement;
    'c-main': CMainElement;
    'c-menu': CMenuElement;
    'c-menu-item': CMenuItemElement;
    'c-menu-label': CMenuLabelElement;
    'c-message': CMessageElement;
    'c-modal': CModalElement;
    'c-navigation-button': CNavigationButtonElement;
    'c-option': COptionElement;
    'c-option-value': COptionValueElement;
    'c-otp-input': COtpInputElement;
    'c-page': CPageElement;
    'c-pagination': CPaginationElement;
    'c-progress-bar': CProgressBarElement;
    'c-radio': CRadioElement;
    'c-radio-group': CRadioGroupElement;
    'c-row': CRowElement;
    'c-select': CSelectElement;
    'c-side-navigation': CSideNavigationElement;
    'c-side-navigation-item': CSideNavigationItemElement;
    'c-side-navigation-title': CSideNavigationTitleElement;
    'c-slider': CSliderElement;
    'c-spacer': CSpacerElement;
    'c-spinner': CSpinnerElement;
    'c-status': CStatusElement;
    'c-step': CStepElement;
    'c-steps': CStepsElement;
    'c-sub-navigation-item': CSubNavigationItemElement;
    'c-swiper': CSwiperElement;
    'c-swiper-tab': CSwiperTabElement;
    'c-switch': CSwitchElement;
    'c-tab': CTabElement;
    'c-tab-buttons': CTabButtonsElement;
    'c-tab-item': CTabItemElement;
    'c-tab-items': CTabItemsElement;
    'c-table': CTableElement;
    'c-tabs': CTabsElement;
    'c-tag': CTagElement;
    'c-tags': CTagsElement;
    'c-text-field': CTextFieldElement;
    'c-toast': CToastElement;
    'c-toasts': CToastsElement;
    'c-toolbar': CToolbarElement;
  }
}
