/* eslint-disable */
/**
 * GENERATED by scripts/generate.mjs from the csc-ui Custom Elements
 * Manifest — do not edit. Regenerate with `pnpm run generate`.
 */

import { createComponent, type EventName } from '@lit/react';
import {
  defineCustomElements,
  type CAccordionElement,
  type CAccordionElementEventMap,
  type CAccordionItemElement,
  type CAccordionItemElementEventMap,
  type CAlertElement,
  type CAlertElementEventMap,
  type CAutocompleteElement,
  type CAutocompleteElementEventMap,
  type CBadgeElement,
  type CButtonElement,
  type CButtonGroupElement,
  type CButtonGroupElementEventMap,
  type CCardElement,
  type CCardActionsElement,
  type CCardContentElement,
  type CCardTitleElement,
  type CCheckboxElement,
  type CCheckboxElementEventMap,
  type CCscLogoElement,
  type CDataTableElement,
  type CDataTableElementEventMap,
  type CDividerElement,
  type CIconElement,
  type CIconButtonElement,
  type CInputElement,
  type CLinkElement,
  type CListElement,
  type CListItemElement,
  type CListItemTitleElement,
  type CLoaderElement,
  type CLoginButtonElement,
  type CLoginButtonsElement,
  type CLoginCardElement,
  type CLoginCardActionsElement,
  type CLoginCardContentElement,
  type CLoginCardTitleElement,
  type CMainElement,
  type CMenuElement,
  type CMenuElementEventMap,
  type CMenuItemElement,
  type CMenuLabelElement,
  type CMessageElement,
  type CModalElement,
  type CModalElementEventMap,
  type CNavigationButtonElement,
  type COptionElement,
  type COptionValueElement,
  type COtpInputElement,
  type COtpInputElementEventMap,
  type CPageElement,
  type CPaginationElement,
  type CPaginationElementEventMap,
  type CPopoverElement,
  type CPopoverElementEventMap,
  type CProgressBarElement,
  type CProgressCircleElement,
  type CRadioElement,
  type CRadioElementEventMap,
  type CRadioGroupElement,
  type CRadioGroupElementEventMap,
  type CSelectElement,
  type CSelectElementEventMap,
  type CSideNavigationElement,
  type CSideNavigationElementEventMap,
  type CSideNavigationItemElement,
  type CSideNavigationItemElementEventMap,
  type CSideNavigationTitleElement,
  type CSliderElement,
  type CSliderElementEventMap,
  type CSpinnerElement,
  type CStatusElement,
  type CStepElement,
  type CStepsElement,
  type CSubNavigationItemElement,
  type CSwitchElement,
  type CSwitchElementEventMap,
  type CTabElement,
  type CTabElementEventMap,
  type CTabButtonsElement,
  type CTabButtonsElementEventMap,
  type CTabItemElement,
  type CTabItemElementEventMap,
  type CTabItemsElement,
  type CTableElement,
  type CTabsElement,
  type CTabsElementEventMap,
  type CTagElement,
  type CTagElementEventMap,
  type CTagsElement,
  type CTextFieldElement,
  type CTextFieldElementEventMap,
  type CToastElement,
  type CToastElementEventMap,
  type CToastsElement,
  type CToolbarElement,
  type CTooltipElement,
  type CTooltipElementEventMap,
} from '@cscfi/csc-ui';
import * as React from 'react';

// Register the custom elements once on the client. During SSR the bare tags
// render as-is and upgrade on the client.
if (typeof customElements !== 'undefined') {
  defineCustomElements();
}

/**
 * The upgraded element class, typed as its generated element interface.
 * `createComponent` probes `elementClass.prototype` to route React props to
 * DOM properties; on the server (no custom element registry) an empty class
 * makes every prop render as an attribute, which hydration then corrects.
 */
const elementClass = <T extends HTMLElement>(tag: string) =>
  (typeof customElements !== 'undefined'
    ? customElements.get(tag)
    : class {}) as unknown as { new (): T };

export const CAccordion = createComponent({
  displayName: 'CAccordion',
  elementClass: elementClass<CAccordionElement>('c-accordion'),
  events: {
    onChange: 'change' as EventName<CAccordionElementEventMap['change']>,
    onChangeValue: 'changeValue' as EventName<CAccordionElementEventMap['changeValue']>,
    onInput: 'input' as EventName<CAccordionElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CAccordionElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-accordion',
});

export const CAccordionItem = createComponent({
  displayName: 'CAccordionItem',
  elementClass: elementClass<CAccordionItemElement>('c-accordion-item'),
  events: {
    onItemChange: 'item-change' as EventName<CAccordionItemElementEventMap['item-change']>,
  },
  react: React,
  tagName: 'c-accordion-item',
});

/** A persistent, in-flow status message: a tinted box whose type carries a status family's colours through the icon, heading and accent edge, while the body copy stays neutral. */
export const CAlert = createComponent({
  displayName: 'CAlert',
  elementClass: elementClass<CAlertElement>('c-alert'),
  events: {
    onDismiss: 'dismiss' as EventName<CAlertElementEventMap['dismiss']>,
  },
  react: React,
  tagName: 'c-alert',
});

/** A filterable value-selection component: a readonly value field that opens a popover panel with a search input above the matching options. */
export const CAutocomplete = createComponent({
  displayName: 'CAutocomplete',
  elementClass: elementClass<CAutocompleteElement>('c-autocomplete'),
  events: {
    onChange: 'change' as EventName<CAutocompleteElementEventMap['change']>,
    onChangeQuery: 'change:query' as EventName<CAutocompleteElementEventMap['change:query']>,
    onChangeValue: 'changeValue' as EventName<CAutocompleteElementEventMap['changeValue']>,
    onInput: 'input' as EventName<CAutocompleteElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CAutocompleteElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-autocomplete',
});

export const CBadge = createComponent({
  displayName: 'CBadge',
  elementClass: elementClass<CBadgeElement>('c-badge'),
  react: React,
  tagName: 'c-badge',
});

/** Buttons trigger actions — submitting a form, opening a modal, confirming a choice. Use one primary (default appearance) button per view; secondary actions use the `outlined`, `ghost` or `text` appearances. */
export const CButton = createComponent({
  displayName: 'CButton',
  elementClass: elementClass<CButtonElement>('c-button'),
  react: React,
  tagName: 'c-button',
});

/** A button group is a segmented control: a compact group of choices rendered as plain `c-button` children, where activating a button takes effect immediately (switching a view, picking a billing period). Selection is exclusive by default; set `multiple` to let several buttons be active at once. Give the group a `label` when it acts as a form field so the choice it represents is named for every user. */
export const CButtonGroup = createComponent({
  displayName: 'CButtonGroup',
  elementClass: elementClass<CButtonGroupElement>('c-button-group'),
  events: {
    onChange: 'change' as EventName<CButtonGroupElementEventMap['change']>,
    onInput: 'input' as EventName<CButtonGroupElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CButtonGroupElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-button-group',
});

export const CCard = createComponent({
  displayName: 'CCard',
  elementClass: elementClass<CCardElement>('c-card'),
  react: React,
  tagName: 'c-card',
});

export const CCardActions = createComponent({
  displayName: 'CCardActions',
  elementClass: elementClass<CCardActionsElement>('c-card-actions'),
  react: React,
  tagName: 'c-card-actions',
});

export const CCardContent = createComponent({
  displayName: 'CCardContent',
  elementClass: elementClass<CCardContentElement>('c-card-content'),
  react: React,
  tagName: 'c-card-content',
});

export const CCardTitle = createComponent({
  displayName: 'CCardTitle',
  elementClass: elementClass<CCardTitleElement>('c-card-title'),
  react: React,
  tagName: 'c-card-title',
});

/** A form control for a single on/off choice: a native checkbox with a label, an optional hint, and validation messaging. */
export const CCheckbox = createComponent({
  displayName: 'CCheckbox',
  elementClass: elementClass<CCheckboxElement>('c-checkbox'),
  events: {
    onChange: 'change' as EventName<CCheckboxElementEventMap['change']>,
    onChangeValue: 'changeValue' as EventName<CCheckboxElementEventMap['changeValue']>,
    onInput: 'input' as EventName<CCheckboxElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CCheckboxElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-checkbox',
});

export const CCscLogo = createComponent({
  displayName: 'CCscLogo',
  elementClass: elementClass<CCscLogoElement>('c-csc-logo'),
  react: React,
  tagName: 'c-csc-logo',
});

export const CDataTable = createComponent({
  displayName: 'CDataTable',
  elementClass: elementClass<CDataTableElement>('c-data-table'),
  events: {
    onChangeExpanded: 'change:expanded' as EventName<CDataTableElementEventMap['change:expanded']>,
    onChangePage: 'change:page' as EventName<CDataTableElementEventMap['change:page']>,
    onChangePageSize: 'change:page-size' as EventName<CDataTableElementEventMap['change:page-size']>,
    onChangeSelected: 'change:selected' as EventName<CDataTableElementEventMap['change:selected']>,
    onChangeSort: 'change:sort' as EventName<CDataTableElementEventMap['change:sort']>,
  },
  react: React,
  tagName: 'c-data-table',
});

export const CDivider = createComponent({
  displayName: 'CDivider',
  elementClass: elementClass<CDividerElement>('c-divider'),
  react: React,
  tagName: 'c-divider',
});

export const CIcon = createComponent({
  displayName: 'CIcon',
  elementClass: elementClass<CIconElement>('c-icon'),
  react: React,
  tagName: 'c-icon',
});

export const CIconButton = createComponent({
  displayName: 'CIconButton',
  elementClass: elementClass<CIconButtonElement>('c-icon-button'),
  react: React,
  tagName: 'c-icon-button',
});

export const CInput = createComponent({
  displayName: 'CInput',
  elementClass: elementClass<CInputElement>('c-input'),
  react: React,
  tagName: 'c-input',
});

/** Basic hyperlink component */
export const CLink = createComponent({
  displayName: 'CLink',
  elementClass: elementClass<CLinkElement>('c-link'),
  react: React,
  tagName: 'c-link',
});

export const CList = createComponent({
  displayName: 'CList',
  elementClass: elementClass<CListElement>('c-list'),
  react: React,
  tagName: 'c-list',
});

export const CListItem = createComponent({
  displayName: 'CListItem',
  elementClass: elementClass<CListItemElement>('c-list-item'),
  react: React,
  tagName: 'c-list-item',
});

export const CListItemTitle = createComponent({
  displayName: 'CListItemTitle',
  elementClass: elementClass<CListItemTitleElement>('c-list-item-title'),
  react: React,
  tagName: 'c-list-item-title',
});

/** A loader component that fills the nearest containing element that has css-property position set to 'relative' */
export const CLoader = createComponent({
  displayName: 'CLoader',
  elementClass: elementClass<CLoaderElement>('c-loader'),
  react: React,
  tagName: 'c-loader',
});

export const CLoginButton = createComponent({
  displayName: 'CLoginButton',
  elementClass: elementClass<CLoginButtonElement>('c-login-button'),
  react: React,
  tagName: 'c-login-button',
});

export const CLoginButtons = createComponent({
  displayName: 'CLoginButtons',
  elementClass: elementClass<CLoginButtonsElement>('c-login-buttons'),
  react: React,
  tagName: 'c-login-buttons',
});

export const CLoginCard = createComponent({
  displayName: 'CLoginCard',
  elementClass: elementClass<CLoginCardElement>('c-login-card'),
  react: React,
  tagName: 'c-login-card',
});

export const CLoginCardActions = createComponent({
  displayName: 'CLoginCardActions',
  elementClass: elementClass<CLoginCardActionsElement>('c-login-card-actions'),
  react: React,
  tagName: 'c-login-card-actions',
});

export const CLoginCardContent = createComponent({
  displayName: 'CLoginCardContent',
  elementClass: elementClass<CLoginCardContentElement>('c-login-card-content'),
  react: React,
  tagName: 'c-login-card-content',
});

export const CLoginCardTitle = createComponent({
  displayName: 'CLoginCardTitle',
  elementClass: elementClass<CLoginCardTitleElement>('c-login-card-title'),
  react: React,
  tagName: 'c-login-card-title',
});

/** Wrapper component for the whole page */
export const CMain = createComponent({
  displayName: 'CMain',
  elementClass: elementClass<CMainElement>('c-main'),
  react: React,
  tagName: 'c-main',
});

export const CMenu = createComponent({
  displayName: 'CMenu',
  elementClass: elementClass<CMenuElement>('c-menu'),
  events: {
    onChangeOpen: 'change:open' as EventName<CMenuElementEventMap['change:open']>,
    onSelect: 'select' as EventName<CMenuElementEventMap['select']>,
  },
  react: React,
  tagName: 'c-menu',
});

/** A single command in a `c-menu`. */
export const CMenuItem = createComponent({
  displayName: 'CMenuItem',
  elementClass: elementClass<CMenuItemElement>('c-menu-item'),
  react: React,
  tagName: 'c-menu-item',
});

/** Section label for a group of `c-menu-item`s. */
export const CMenuLabel = createComponent({
  displayName: 'CMenuLabel',
  elementClass: elementClass<CMenuLabelElement>('c-menu-label'),
  react: React,
  tagName: 'c-menu-label',
});

export const CMessage = createComponent({
  displayName: 'CMessage',
  elementClass: elementClass<CMessageElement>('c-message'),
  react: React,
  tagName: 'c-message',
});

/** Modals interrupt the page for a task that must be completed (or explicitly cancelled) before continuing — confirmations, short forms, destructive-action warnings. The slotted content is typically a `c-card`. */
export const CModal = createComponent({
  displayName: 'CModal',
  elementClass: elementClass<CModalElement>('c-modal'),
  events: {
    onChangeValue: 'changeValue' as EventName<CModalElementEventMap['changeValue']>,
    onInput: 'input' as EventName<CModalElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CModalElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-modal',
});

export const CNavigationButton = createComponent({
  displayName: 'CNavigationButton',
  elementClass: elementClass<CNavigationButtonElement>('c-navigation-button'),
  react: React,
  tagName: 'c-navigation-button',
});

export const COption = createComponent({
  displayName: 'COption',
  elementClass: elementClass<COptionElement>('c-option'),
  react: React,
  tagName: 'c-option',
});

export const COptionValue = createComponent({
  displayName: 'COptionValue',
  elementClass: elementClass<COptionValueElement>('c-option-value'),
  react: React,
  tagName: 'c-option-value',
});

export const COtpInput = createComponent({
  displayName: 'COtpInput',
  elementClass: elementClass<COtpInputElement>('c-otp-input'),
  events: {
    onChangeValue: 'changeValue' as EventName<COtpInputElementEventMap['changeValue']>,
    onCompletion: 'completion' as EventName<COtpInputElementEventMap['completion']>,
    onInput: 'input' as EventName<COtpInputElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<COtpInputElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-otp-input',
});

export const CPage = createComponent({
  displayName: 'CPage',
  elementClass: elementClass<CPageElement>('c-page'),
  react: React,
  tagName: 'c-page',
});

export const CPagination = createComponent({
  displayName: 'CPagination',
  elementClass: elementClass<CPaginationElement>('c-pagination'),
  events: {
    onChangeValue: 'changeValue' as EventName<CPaginationElementEventMap['changeValue']>,
    onInput: 'input' as EventName<CPaginationElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CPaginationElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-pagination',
});

/** A click-opened, non-modal surface anchored to its trigger, floating in the top layer; its content may be interactive. */
export const CPopover = createComponent({
  displayName: 'CPopover',
  elementClass: elementClass<CPopoverElement>('c-popover'),
  events: {
    onChangeOpen: 'change:open' as EventName<CPopoverElementEventMap['change:open']>,
  },
  react: React,
  tagName: 'c-popover',
});

/** A horizontal progress bar that fills a track to a known completion percentage, with an optional details line showing the value and a label. */
export const CProgressBar = createComponent({
  displayName: 'CProgressBar',
  elementClass: elementClass<CProgressBarElement>('c-progress-bar'),
  react: React,
  tagName: 'c-progress-bar',
});

/** A circular progress indicator that draws a known completion percentage as an arc around a track — the circular counterpart of `c-progress-bar`. */
export const CProgressCircle = createComponent({
  displayName: 'CProgressCircle',
  elementClass: elementClass<CProgressCircleElement>('c-progress-circle'),
  react: React,
  tagName: 'c-progress-circle',
});

/** A single radio option inside a `c-radio-group`: a native radio input whose default slot is its clickable, announced label. */
export const CRadio = createComponent({
  displayName: 'CRadio',
  elementClass: elementClass<CRadioElement>('c-radio'),
  events: {
    onChange: 'change' as EventName<CRadioElementEventMap['change']>,
  },
  react: React,
  tagName: 'c-radio',
});

/** A radio group is a set of mutually exclusive choices where exactly one can be selected, authored as slotted `c-radio` children. Give the group a `label` so the choice it represents is named for every user, and a `hint` describing how to answer. */
export const CRadioGroup = createComponent({
  displayName: 'CRadioGroup',
  elementClass: elementClass<CRadioGroupElement>('c-radio-group'),
  events: {
    onChangeValue: 'changeValue' as EventName<CRadioGroupElementEventMap['changeValue']>,
    onInput: 'input' as EventName<CRadioGroupElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CRadioGroupElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-radio-group',
});

export const CSelect = createComponent({
  displayName: 'CSelect',
  elementClass: elementClass<CSelectElement>('c-select'),
  events: {
    onChangeValue: 'changeValue' as EventName<CSelectElementEventMap['changeValue']>,
    onInput: 'input' as EventName<CSelectElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CSelectElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-select',
});

export const CSideNavigation = createComponent({
  displayName: 'CSideNavigation',
  elementClass: elementClass<CSideNavigationElement>('c-side-navigation'),
  events: {
    onChangeMenuVisible: 'change:menu-visible' as EventName<CSideNavigationElementEventMap['change:menu-visible']>,
  },
  react: React,
  tagName: 'c-side-navigation',
});

export const CSideNavigationItem = createComponent({
  displayName: 'CSideNavigationItem',
  elementClass: elementClass<CSideNavigationItemElement>('c-side-navigation-item'),
  events: {
    onItemChange: 'itemChange' as EventName<CSideNavigationItemElementEventMap['itemChange']>,
  },
  react: React,
  tagName: 'c-side-navigation-item',
});

export const CSideNavigationTitle = createComponent({
  displayName: 'CSideNavigationTitle',
  elementClass: elementClass<CSideNavigationTitleElement>('c-side-navigation-title'),
  react: React,
  tagName: 'c-side-navigation-title',
});

export const CSlider = createComponent({
  displayName: 'CSlider',
  elementClass: elementClass<CSliderElement>('c-slider'),
  events: {
    onChangeValue: 'changeValue' as EventName<CSliderElementEventMap['changeValue']>,
    onInput: 'input' as EventName<CSliderElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CSliderElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-slider',
});

/** A circular indeterminate activity indicator — pure motion with no value, for waits of unknown duration. */
export const CSpinner = createComponent({
  displayName: 'CSpinner',
  elementClass: elementClass<CSpinnerElement>('c-spinner'),
  react: React,
  tagName: 'c-spinner',
});

export const CStatus = createComponent({
  displayName: 'CStatus',
  elementClass: elementClass<CStatusElement>('c-status'),
  react: React,
  tagName: 'c-status',
});

export const CStep = createComponent({
  displayName: 'CStep',
  elementClass: elementClass<CStepElement>('c-step'),
  react: React,
  tagName: 'c-step',
});

export const CSteps = createComponent({
  displayName: 'CSteps',
  elementClass: elementClass<CStepsElement>('c-steps'),
  react: React,
  tagName: 'c-steps',
});

export const CSubNavigationItem = createComponent({
  displayName: 'CSubNavigationItem',
  elementClass: elementClass<CSubNavigationItemElement>('c-sub-navigation-item'),
  react: React,
  tagName: 'c-sub-navigation-item',
});

/** A toggle for a binary setting that takes effect immediately: a native switch control with a label, an optional hint, and validation messaging. */
export const CSwitch = createComponent({
  displayName: 'CSwitch',
  elementClass: elementClass<CSwitchElement>('c-switch'),
  events: {
    onChange: 'change' as EventName<CSwitchElementEventMap['change']>,
    onChangeValue: 'changeValue' as EventName<CSwitchElementEventMap['changeValue']>,
    onInput: 'input' as EventName<CSwitchElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CSwitchElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-switch',
});

export const CTab = createComponent({
  displayName: 'CTab',
  elementClass: elementClass<CTabElement>('c-tab'),
  events: {
    onTabChange: 'tabChange' as EventName<CTabElementEventMap['tabChange']>,
    onTabFocus: 'tabFocus' as EventName<CTabElementEventMap['tabFocus']>,
  },
  react: React,
  tagName: 'c-tab',
});

/** Tab buttons present a `c-tabs` tab list as a segmented control instead of the underlined tab row. Author it only inside `<c-tabs>`, with plain `<c-button>` children whose `value`s match the `c-tab-item` panels; `c-tabs` owns the active value and pushes it down. */
export const CTabButtons = createComponent({
  displayName: 'CTabButtons',
  elementClass: elementClass<CTabButtonsElement>('c-tab-buttons'),
  events: {
    onTabChange: 'tabChange' as EventName<CTabButtonsElementEventMap['tabChange']>,
  },
  react: React,
  tagName: 'c-tab-buttons',
});

export const CTabItem = createComponent({
  displayName: 'CTabItem',
  elementClass: elementClass<CTabItemElement>('c-tab-item'),
  events: {
    onContentChange: 'contentChange' as EventName<CTabItemElementEventMap['contentChange']>,
  },
  react: React,
  tagName: 'c-tab-item',
});

export const CTabItems = createComponent({
  displayName: 'CTabItems',
  elementClass: elementClass<CTabItemsElement>('c-tab-items'),
  react: React,
  tagName: 'c-tab-items',
});

/** A styled wrapper for a table you author yourself: slot in a plain `<table>` and c-table gives it the CSC look plus an optional responsive card layout on narrow screens. The table stays in your own DOM — your stylesheets, your framework's rendering, and `::part()` selectors on components nested in cells (a `c-tag` status chip, a `c-pagination` footer) all keep working. */
export const CTable = createComponent({
  displayName: 'CTable',
  elementClass: elementClass<CTableElement>('c-table'),
  react: React,
  tagName: 'c-table',
});

export const CTabs = createComponent({
  displayName: 'CTabs',
  elementClass: elementClass<CTabsElement>('c-tabs'),
  events: {
    onChangeValue: 'changeValue' as EventName<CTabsElementEventMap['changeValue']>,
    onInput: 'input' as EventName<CTabsElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CTabsElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-tabs',
});

export const CTag = createComponent({
  displayName: 'CTag',
  elementClass: elementClass<CTagElement>('c-tag'),
  events: {
    onClose: 'close' as EventName<CTagElementEventMap['close']>,
  },
  react: React,
  tagName: 'c-tag',
});

export const CTags = createComponent({
  displayName: 'CTags',
  elementClass: elementClass<CTagsElement>('c-tags'),
  react: React,
  tagName: 'c-tags',
});

export const CTextField = createComponent({
  displayName: 'CTextField',
  elementClass: elementClass<Omit<CTextFieldElement, 'autocorrect'> & HTMLElement>('c-text-field'),
  events: {
    onChange: 'change' as EventName<CTextFieldElementEventMap['change']>,
    onChangeValue: 'changeValue' as EventName<CTextFieldElementEventMap['changeValue']>,
    onInput: 'input' as EventName<CTextFieldElementEventMap['input']>,
    onUpdateValue: 'update:value' as EventName<CTextFieldElementEventMap['update:value']>,
  },
  react: React,
  tagName: 'c-text-field',
});

/** A single toast notification, rendered and managed by c-toasts */
export const CToast = createComponent({
  displayName: 'CToast',
  elementClass: elementClass<CToastElement>('c-toast'),
  events: {
    onClose: 'close' as EventName<CToastElementEventMap['close']>,
  },
  react: React,
  tagName: 'c-toast',
});

/** Toasts are passive, transient notifications — operation results, background progress — stacked and managed by a single `c-toasts` container via its `addToast` / `removeToast` methods. */
export const CToasts = createComponent({
  displayName: 'CToasts',
  elementClass: elementClass<CToastsElement>('c-toasts'),
  react: React,
  tagName: 'c-toasts',
});

export const CToolbar = createComponent({
  displayName: 'CToolbar',
  elementClass: elementClass<CToolbarElement>('c-toolbar'),
  react: React,
  tagName: 'c-toolbar',
});

/** A non-interactive text hint shown when its trigger is hovered or keyboard-focused, floating in the top layer on the inverted surface tier. */
export const CTooltip = createComponent({
  displayName: 'CTooltip',
  elementClass: elementClass<CTooltipElement>('c-tooltip'),
  events: {
    onChangeOpen: 'change:open' as EventName<CTooltipElementEventMap['change:open']>,
  },
  react: React,
  tagName: 'c-tooltip',
});
