name: Merge the automated pull request

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: The pull request id
        required: true

jobs:
  githubrelease:
    runs-on: ubuntu-latest

    steps:
      - name: Automerge the PR
        if: github.event.inputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          pull-request-number: ${{ github.event.inputs.pr_number }}
          merge-method: merge

      - name: Build Github release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git fetch --tags
          npx auto release --base-branch master
