name: Release Action

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') && github.event.pull_request.merged == true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: NPM version bump (patch)
        run: |
          git config --global user.email "suiteamsui@gmail.com"
          git config --global user.name "My CSC Team"
          npm version patch -m "Bump version to %s"
        if: contains(github.event.pull_request.labels.*.name, 'patch')

      - name: Install dependencies and build packages
        run: |
          npm i && npm run predeploy

      - name: Publish Package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - uses: Saionaro/extract-package-version@v1.2.1
        id: package-version

      - name: Push GIT tag
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ steps.package-version.outputs.version }}
          message: '${{ steps.package-version.outputs.version }}'

      - name: setup Firebase
        uses: pocket-apps/action-setup-firebase@v2
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Publish documentation
        run: npm run deploy:documentation

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RELEASE_NAME_PREFIX: 'Release: '
