name: Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') && github.event.pull_request.merged == true"
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm i
          npm run build
          npm run style-dictionary:build:prod
          curl \
            -X PUT \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/CSCfi/csc-ui/branches/master/protection \
            -d '{"enforce_admins": null,"required_linear_history": false,"allow_force_pushes": false,"allow_deletions": false,"block_creations": false,"required_conversation_resolution": false,"lock_branch": false,"allow_fork_syncing": false,"required_pull_request_reviews":null,"required_status_checks":null,"restrictions":null}'
          npx auto latest
          curl \
            -X PUT \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/CSCfi/csc-ui/branches/master/protection \
            -d '{"enforce_admins": null,"required_status_checks":null,"restrictions":null,"required_pull_request_reviews":{"dismiss_stale_reviews": false,"require_code_owner_reviews": false,"require_last_push_approval": true,"required_approving_review_count": 1}}'
          npm run deploy:documentation
