/* eslint-disable */
/**
 * GENERATED by scripts/generate-chart-data.mjs from
 * tokens/semantic/{light,dark}.json — do not edit.
 * Regenerate with `pnpm run chart:generate`; `pnpm run lint:chart` fails
 * the build when this file is stale.
 *
 * The chart tokens (ADR-0030) as importable data (ADR-0040): the twelve
 * series slots and the chart anatomy roles per theme mode. Values are the
 * frozen, validated set — they never follow a consumer's `--c-chart-*`
 * overrides. Pair with `themeMode()` to pick the mode on screen.
 */

import type { ThemeMode } from './themeMode';

/** The twelve series slots in slot order (`chart-1` … `chart-12`). */
export type ChartSlots = readonly [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
];

/** The chart anatomy roles: plot background, gridlines/axes, tick labels. */
export interface ChartAnatomy {
  readonly surface: string;
  readonly grid: string;
  readonly axis: string;
}

/**
 * Series slots per theme mode as `oklch(L C H)` strings — the palette's own
 * colour space, ready for CSS, SVG and canvas `fillStyle`, and the exact
 * string the `--c-chart-*` variable holds (ADR-0041). Each round-trips to
 * the `#rrggbb` in `chartSlotsHex`.
 */
export const chartSlots: Readonly<Record<ThemeMode, ChartSlots>> = {
  light: [
    'oklch(0.6534 0.1710 247.9336)',
    'oklch(0.5906 0.1462 343.7182)',
    'oklch(0.6697 0.1291 89.0072)',
    'oklch(0.5828 0.1563 304.1567)',
    'oklch(0.6535 0.1224 175.0621)',
    'oklch(0.5492 0.1452 15.2354)',
    'oklch(0.6591 0.1084 215.9066)',
    'oklch(0.5509 0.1711 271.9308)',
    'oklch(0.6689 0.1550 335.8160)',
    'oklch(0.6158 0.1381 113.7300)',
    'oklch(0.6594 0.1561 281.6578)',
    'oklch(0.5889 0.1004 195.6438)',
  ],
  dark: [
    'oklch(0.6504 0.1710 247.9858)',
    'oklch(0.5920 0.1445 343.8493)',
    'oklch(0.6696 0.1303 89.2281)',
    'oklch(0.5861 0.1562 304.1845)',
    'oklch(0.6697 0.1216 175.8180)',
    'oklch(0.5874 0.1449 15.7250)',
    'oklch(0.6696 0.1134 215.6049)',
    'oklch(0.5788 0.1701 271.6728)',
    'oklch(0.6689 0.1550 335.8160)',
    'oklch(0.6126 0.1374 113.7550)',
    'oklch(0.6562 0.1563 281.6216)',
    'oklch(0.5979 0.1019 195.6274)',
  ],
};

/**
 * Series slots per theme mode as `#rrggbb` — for chart libraries that do
 * their own colour maths in sRGB (ECharts, Chart.js) and cannot parse
 * `oklch()`. Same colours and order as `chartSlots`.
 */
export const chartSlotsHex: Readonly<Record<ThemeMode, ChartSlots>> = {
  light: [
    '#1295f2',
    '#b75593',
    '#b5901d',
    '#905fc5',
    '#05a88c',
    '#b64655',
    '#26a2bc',
    '#5165d4',
    '#ce6cb9',
    '#858d00',
    '#8483ee',
    '#008f90',
  ],
  dark: [
    '#1094f1',
    '#b75693',
    '#b5901a',
    '#9160c6',
    '#17ad92',
    '#c3525f',
    '#1da6c1',
    '#586edd',
    '#ce6cb9',
    '#848c00',
    '#8382ed',
    '#009293',
  ],
};

/** Chart anatomy roles per theme mode as `oklch(L C H)` strings. */
export const chartAnatomy: Readonly<Record<ThemeMode, ChartAnatomy>> = {
  light: {
    surface: 'oklch(1.0000 0.0000 0.0000)',
    grid: 'oklch(0.9088 0.0035 247.8616)',
    axis: 'oklch(0.6202 0.0140 229.0608)',
  },
  dark: {
    surface: 'oklch(0.3028 0.0092 248.1305)',
    grid: 'oklch(0.3754 0.0117 243.1204)',
    axis: 'oklch(0.7599 0.0117 243.7024)',
  },
};

/** Chart anatomy roles per theme mode as `#rrggbb`. */
export const chartAnatomyHex: Readonly<Record<ThemeMode, ChartAnatomy>> = {
  light: {
    surface: '#ffffff',
    grid: '#dfe1e3',
    axis: '#7e888d',
  },
  dark: {
    surface: '#2b2f33',
    grid: '#3c4247',
    axis: '#abb2b8',
  },
};
