/**
 * React wrapper codegen.
 *
 * Reads the csc-ui-next Custom Elements Manifest and emits src/components.ts:
 * one `@lit/react` `createComponent` call per consumer-authorable component.
 *
 *   - Prop typing comes from the element interfaces the library generates
 *     into its tag-name map (`CSwitchElement` etc.) — `createComponent`
 *     derives the React props from the element type.
 *   - Event typing anchors on the exported `C*ElementEventMap` interfaces
 *     (`EventName<CSwitchElementEventMap['changeValue']>`), so event `detail`
 *     types stay correct without re-declaring them here.
 *
 * The output is committed for reviewability; `pnpm run build` regenerates it
 * before compiling, so it can never ship stale.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = path.resolve(fileURLToPath(import.meta.url), '../..');

const manifestPath = path.resolve(
  packageRoot,
  '../csc-ui-next/dist/custom-elements.json',
);

if (!existsSync(manifestPath)) {
  console.error(
    `custom-elements.json not found at ${manifestPath} — build @cscfi/csc-ui-next first`,
  );
  process.exit(1);
}

/**
 * Elements the consumer never authors (instantiated internally by a parent).
 * Keep in sync with INTERNAL_ONLY in the docs' useManifest.ts.
 */
const INTERNAL_ONLY = new Set(['c-dropdown']);

/**
 * Props that shadow an HTMLElement member `@lit/react` cannot reconcile, per
 * tag. `HTMLElement.autocorrect` is a NON-optional `boolean`; c-text-field's
 * `autocorrect` is an optional `boolean` (unset = browser per-input-type
 * default), and `boolean | undefined` is not assignable to `boolean`, so the
 * element interface fails `@lit/react`'s `I extends HTMLElement` constraint.
 * The wrapper re-adds the lib member for these names so the constraint holds;
 * the React prop stays optional regardless. A new collision fails the tsc
 * step loudly — add the prop here when that happens.
 */
const DOM_LIB_COLLISIONS = new Map([['c-text-field', ['autocorrect']]]);

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));

const components = manifest.modules
  .flatMap((mod) => mod.declarations ?? [])
  .filter((decl) => decl.customElement && !INTERNAL_ONLY.has(decl.tagName))
  .sort((a, b) => a.tagName.localeCompare(b.tagName));

/** `update:value` → `onUpdateValue`, `changeValue` → `onChangeValue`. */
const reactEventName = (name) =>
  `on${name
    .split(/[:-]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')}`;

const jsdoc = (description) => {
  if (!description) return '';

  const body = description.replace(/\*\//g, '*\\/');

  const lines = body.split('\n');

  if (lines.length === 1) return `/** ${lines[0]} */\n`;

  return `/**\n${lines.map((line) => ` * ${line}`.trimEnd()).join('\n')}\n */\n`;
};

const blocks = [];

const elementImports = [];

for (const component of components) {
  const collisions = DOM_LIB_COLLISIONS.get(component.tagName);

  const elementName = `${component.name}Element`;

  const elementType = collisions
    ? `Omit<${elementName}, ${collisions
        .map((name) => `'${name}'`)
        .join(' | ')}> & HTMLElement`
    : elementName;

  const eventMapName = `${elementName}EventMap`;

  elementImports.push(`type ${elementName}`);

  const events = component.events ?? [];

  if (events.length) elementImports.push(`type ${eventMapName}`);

  const eventEntries = events
    .map(
      (event) =>
        `    ${reactEventName(event.name)}: '${event.name}' as EventName<${eventMapName}['${event.name}']>,`,
    )
    .join('\n');

  const eventsBlock = events.length
    ? `\n  events: {\n${eventEntries}\n  },`
    : '';

  blocks.push(
    `${jsdoc(component.description)}export const ${component.name} = createComponent({
  displayName: '${component.name}',
  elementClass: elementClass<${elementType}>('${component.tagName}'),${eventsBlock}
  react: React,
  tagName: '${component.tagName}',
});`,
  );
}

const output = `/* eslint-disable */
/**
 * GENERATED by scripts/generate.mjs from the csc-ui-next Custom Elements
 * Manifest — do not edit. Regenerate with \`pnpm run generate\`.
 */

import { createComponent, type EventName } from '@lit/react';
import {
  defineCustomElements,
${elementImports.map((entry) => `  ${entry},`).join('\n')}
} from '@cscfi/csc-ui-next';
import * as React from 'react';

// Register the custom elements once on the client. During SSR the bare tags
// render as-is and upgrade on the client.
if (typeof customElements !== 'undefined') {
  defineCustomElements();
}

/**
 * The upgraded element class, typed as its generated element interface.
 * \`createComponent\` probes \`elementClass.prototype\` to route React props to
 * DOM properties; on the server (no custom element registry) an empty class
 * makes every prop render as an attribute, which hydration then corrects.
 */
const elementClass = <T extends HTMLElement>(tag: string) =>
  (typeof customElements !== 'undefined'
    ? customElements.get(tag)
    : class {}) as unknown as { new (): T };

${blocks.join('\n\n')}
`;

const target = path.join(packageRoot, 'src/components.ts');

mkdirSync(path.dirname(target), { recursive: true });

const previous = existsSync(target) ? readFileSync(target, 'utf8') : '';

if (previous !== output) {
  writeFileSync(target, output);
  console.log(
    `components.ts: generated ${components.length} React components`,
  );
} else {
  console.log(`components.ts: up to date (${components.length} components)`);
}
