import { afterEach, beforeEach, expect } from 'vitest';

// Document-level tokens (generated by `style-dictionary:build`, which the
// `test` script runs first) and the stable page frame.
import '../styles/css/tokens.css';
import './harness.css';
import { resetDefaults } from '../shared/appDefaults';
import { resetTheme } from '../theme/applyTheme';
import { consoleSpy, setThemeMode } from './harness';

// Registration is deliberately NOT done here: `mount()` registers on demand.
// The dist smoke needs a registry the source build has not touched, and a spec
// may want to observe the pre-upgrade window.

beforeEach(() => {
  setThemeMode('light');
  consoleSpy.start();
});

afterEach(() => {
  const unexpected = consoleSpy.stop();
  document.body.replaceChildren(); // disconnect → Vue unmount → popovers hidden
  resetDefaults();
  resetTheme();
  setThemeMode('light');
  expect(unexpected, 'console.error / Vue warnings during the test').toEqual(
    [],
  );
});
