on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action
          path: 'packages/csc-ui'
          changelog-path: 'CHANGELOG.md'

      - name: Checkout repository
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}

      - name: Enable corepack (pnpm)
        run: corepack enable
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.releases_created }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        if: ${{ steps.release.outputs.releases_created }}

      - name: Build & publish csc-ui
        run: |
          pnpm --filter @cscfi/csc-ui run build
          pnpm --filter @cscfi/csc-ui publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.releases_created }}

      - name: Build & publish csc-ui-react
        run: |
          pnpm --filter @cscfi/csc-ui-react run build
          cd packages/csc-ui-react
          version="$(node ../csc-ui/scripts/getLatestVersion.js)"
          pnpm version "$version" --no-git-tag-version
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.releases_created }}
